### ISSUE TITLE
NullReferenceException at Microsoft.Identity.Client.Platforms.netcore.NetCoreCryptographyManager.SignWithCertificate in Azure only

### ISSUE THREAD

**Issue by MrDoctorJ** [AzureAD/microsoft-authentication-library-for-dotnet#1046]
**Which Version of MSAL are you using ?**
MSAL 2.7.1, also used MSAL preview 3.0.2-preview and same issue happens.

**Platform**
netcore, Azure app service

**What authentication flow has the issue?**
* Web App
    * [x ] Authorization code

Other?
Authenticating with a self-signed certificate through Azure app only client id and client secret.

**Is this a new or existing app?**
This is a new app. 

**Repro**
Getting a NullReferenceException inside AcquireTokenForClientAsync when the app is deployed to Azure. Everything works fine when developing locally. I've used both 2.7.1 and 3.0.2-preview versions of Microsoft.Identity.Client and both throw the same exception. 
I followed [this example](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2) and my code is almost exactly the same. 

The code reads the certificate correctly and all my configuration values (authority, client id, client secret, scope) are all correct. Again, the issue only happens when deployed to Azure.

```csharp
     IConfidentialClientApplication app;

      X509Certificate2 certificate = new X509Certificate2();
      certificate = ReadCertificateByThumbprint(config.AzureAd.CertificateThumbprint);

      // code used with 2.7.1 version
      ClientCredential clientCredentials = new ClientCredential(new ClientAssertionCertificate(certificate));
      app = new ConfidentialClientApplication(config.AzureAd.ClientId, config.AzureAd.Authority, config.AzureAd.CallbackUrl, clientCredentials, null, new TokenCache());
      
      // code used with preview version 3.0.2, also throws same error
      // app = new ConfidentialClientApplication(config.AzureAd.ClientId).
      // app = ConfidentialClientApplicationBuilder.Create(config.AzureAd.ClientId)
      //  .WithCertificate(certificate)
      //  .WithAuthority(new Uri(config.AzureAd.Authority))
      //  .Build();

      string[] scopes = new string[] { config.AzureAd.ScopeUrl };

      AuthenticationResult result = null;
      try
      {
        // error occurs inside AcquireTokenForClientAsync
        result = await app.AcquireTokenForClientAsync(scopes);
      }
```

**Expected behavior**
Expect the app to read a certificate, and get a token using the certificate. 

**Actual behavior**
The app reads the certificate from the Azure store, builds a ConfidentialClientApplication and then throws a NullReferenceException when calling AcquireTokenForClientAsync.

**Additional context/ Logs / Screenshots**
Stacktrace: 

```
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Identity.Client.Platforms.netcore.NetCoreCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate) in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Platforms\netcore\NetCoreCryptographyManager.cs:line 92
   at Microsoft.Identity.Client.ClientAssertionCertificate.Sign(String message) in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Features\ConfidentialClient\ClientAssertionCertificate.cs:line 89
   at Microsoft.Identity.Client.Internal.Jwt.JsonWebToken.Sign(ClientAssertionCertificate credential, Boolean sendCertificate) in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Features\ConfidentialClient\JsonWebToken.cs:line 97
   at Microsoft.Identity.Client.Internal.Requests.AuthenticationRequestParameters.ToParameters() in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Internal\Requests\AuthenticationRequestParameters.cs:line 77
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__22.MoveNext() in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Internal\Requests\RequestBase.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__4.MoveNext() in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Internal\Requests\ClientCredentialRequest.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__16.MoveNext() in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Internal\Requests\RequestBase.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenForClientCommonAsync>d__23.MoveNext() in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Features\ConfidentialClient\ConfidentialClientApplication.cs:line 444
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenForClientAsync>d__9.MoveNext() in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\Features\ConfidentialClient\ConfidentialClientApplication.cs:line 261
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MaintenanceDashboard.Services.AzureCertificateService.<GetAccessTokenAsync>d__2.MoveNext() in C:\Users\Will.Johnson\Documents\GitHub\MaintenanceDashboard\MaintenanceDashboard\Services\AzureCertificateService.cs:line 90}
```

**Comment by henrik-me** [comment]
related? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/857

@MrDoctorJ : Have you tried this with MSAL .NET v4.1?

**Comment by MrDoctorJ** [comment]
@henrik-me I thought I closed this. The issue was that we were using a public certificate and not a private certificate. Changing to a private certificate fixed the issue. But, the error could be more informative to let the user know that its a simple issue.

**Comment by eluchsinger** [comment]
I'm having the same issue with ClientSecret... it's really not a very helpful error message.

**Comment by bgavrilMS** [comment]
@eluchsinger - please open a new bug
