### ISSUE TITLE
Confidential client specifying Instance in ConfidentialClientApplicationOptions fails to retrieve OIDC metadata and acquire tokens

### ISSUE THREAD

**Issue by jelledruyts** [AzureAD/microsoft-authentication-library-for-dotnet#1196]
**Which Version of MSAL are you using ?**
MSAL.NET 3.0.8

**Platform**
netcore22

**What authentication flow has the issue?**
* Web App
    * [X] Authorization code
    * [X] OBO
* Web API
    * [X] OBO

**Is this a new or existing app?**
This is a new app

**Repro**

```csharp
var options = new ConfidentialClientApplicationOptions
{
    ClientId = "<client-id>",
    ClientSecret = "<client-secret>",
    TenantId = "<tenant-id>",
    Instance = "https://login.microsoftonline.com/"
};
var app = ConfidentialClientApplicationBuilder.CreateWithApplicationOptions(options).Build();
var result = app.AcquireTokenForClient(new [] { "https://graph.microsoft.com/.default" }).ExecuteAsync().Result;
```

**Expected behavior**
Get a token result.

**Actual behavior**
Error: "AADSTS90002: Tenant 'v2.0' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator."
The URL being called to retrieve OIDC configuration is in fact missing the tenant:
GET https://login.microsoftonline.com//v2.0/.well-known/openid-configuration
Note the double slash before v2.0 where the tenant id should be.

**Possible Solution**
If you do not set the "Instance" property of the ConfidentialClientApplicationOptions, it actually works fine.

```csharp
var options = new ConfidentialClientApplicationOptions
{
    ClientId = "<client-id>",
    ClientSecret = "<client-secret>",
    TenantId = "<tenant-id>",
    // WORKAROUND - remove: Instance = "https://login.microsoftonline.com/"
};
var app = ConfidentialClientApplicationBuilder.CreateWithApplicationOptions(options).Build();
var result = app.AcquireTokenForClient(new [] { "https://graph.microsoft.com/.default" }).ExecuteAsync().Result;
```

Typically you will however bind the options to Configuration (in the "AzureAd" scope), which usually will have the Instance set. A workaround in that case to explicitly set the Instance property of the options object to null after having bound it to configuration.

```csharp
var options = new ConfidentialClientApplicationOptions();
Configuration.Bind("AzureAd", options);
options.Instance = null; // WORKAROUND
```

But of course this workaround should not be necessary at all.

**Additional context/ Logs / Screenshots**
System.AggregateException: One or more errors occurred. (AADSTS90002: Tenant 'v2.0' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Trace ID: 7c39e109-e555-49e0-a787-7c8ecffd6c00
Correlation ID: 72d57224-074c-4707-bf88-db340ab983c6
Timestamp: 2019-06-03 09:10:50Z) ---> Microsoft.Identity.Client.MsalServiceException: AADSTS90002: Tenant 'v2.0' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Trace ID: 7c39e109-e555-49e0-a787-7c8ecffd6c00
Correlation ID: 72d57224-074c-4707-bf88-db340ab983c6
Timestamp: 2019-06-03 09:10:50Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateErrorResponse(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.AuthorityEndpointResolutionManager.DiscoverEndpointsAsync(String openIdConfigurationEndpoint, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.AuthorityEndpointResolutionManager.ResolveEndpointsAsync(AuthorityInfo authorityInfo, String userPrincipalName, RequestContext requestContext)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.ResolveAuthorityEndpointsAsync()
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Expenses.Api.Startup.ConfigureServices(IServiceCollection services) in C:\Users\jelled\Desktop\Code\IdentitySamplesV2\Repo\Expenses.Api\Startup.cs:line 48
---> (Inner Exception #0) Microsoft.Identity.Client.MsalServiceException: AADSTS90002: Tenant 'v2.0' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Trace ID: 7c39e109-e555-49e0-a787-7c8ecffd6c00
Correlation ID: 72d57224-074c-4707-bf88-db340ab983c6
Timestamp: 2019-06-03 09:10:50Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateErrorResponse(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.AuthorityEndpointResolutionManager.DiscoverEndpointsAsync(String openIdConfigurationEndpoint, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.AuthorityEndpointResolutionManager.ResolveEndpointsAsync(AuthorityInfo authorityInfo, String userPrincipalName, RequestContext requestContext)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.ResolveAuthorityEndpointsAsync()
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
	ErrorCode: invalid_tenant
	StatusCode: 400 
	ResponseBody: {"error":"invalid_tenant","error_description":"AADSTS90002: Tenant 'v2.0' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: 7c39e109-e555-49e0-a787-7c8ecffd6c00\r\nCorrelation ID: 72d57224-074c-4707-bf88-db340ab983c6\r\nTimestamp: 2019-06-03 09:10:50Z","error_codes":[90002],"timestamp":"2019-06-03 09:10:50Z","trace_id":"7c39e109-e555-49e0-a787-7c8ecffd6c00","correlation_id":"72d57224-074c-4707-bf88-db340ab983c6"} 
	Headers: Cache-Control: max-age=86400, private
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
client-request-id: 72d57224-074c-4707-bf88-db340ab983c6
x-ms-request-id: 7c39e109-e555-49e0-a787-7c8ecffd6c00
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: fpc=Ajmd7ED1yHVOizQdkp_b2KY; expires=Wed, 03-Jul-2019 09:10:50 GMT; path=/; secure; HttpOnly, x-ms-gateway-slice=prod; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
Date: Mon, 03 Jun 2019 09:10:49 GMT
<---

**Comment by jmprieur** [comment]
@MarkZuber. FYI

**Comment by MarkZuber** [comment]
This should also work if you have Instance = "https://login.microsoftonline.com" (no trailing space).  I have a repro of this and will fix to handle the double-slash concatenation which is causing the problem.

**Comment by jmprieur** [comment]
@jelledruyts : this is now fixed and available in MSAL.NET 4.1

**Comment by jelledruyts** [comment]
Confirmed that it fixes the problem, thanks @jmprieur !

**Comment by jmprieur** [comment]
Thanks for confirming, @jelledruyts
