### ISSUE TITLE
Multiple uri for WithRedirectUri

### ISSUE THREAD

**Issue by zulander1** [AzureAD/microsoft-authentication-library-for-dotnet#1218]
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.00 ?

**Platform**
netcore

**What authentication flow has the issue?**
* Web App
    * [x ] Authorization code

We have multiple domain for the same site. (using multiple server, with a dns load balancer)

Example:

abc.site.com
abc1.site.com
abc2.site.com
The problem is that when the site is initialized with a domain, it will return a 404 for the other domains. Example: abc1.site.com will works but not abc.site.com and abc2.site.com, if abc2.site.com then abc1.site.com and abc.site.com will not work...

I think it's a cache issue, so how do i allow multi-domain ?

`_app = ConfidentialClientApplicationBuilder.Create(_azureOptions.ClientId).WithRedirectUri(_azureOptions.GetCurrentUrl(httpContextAccessor.HttpContext.Request.Host.Value) + _azureOptions.CallbackPath).WithClientSecret(_azureOptions.ClientSecret).WithAuthority(new Uri(_azureOptions.GetAuthority)).Build();`

the GetCurrentUrl returns the host,of the caller....

```
public string GetCurrentUrl(string url)
{
    string defaultSite = "https://abc1.site.com";
    return BaseUrls.Where(x => x.Equals($"https://{url}", System.StringComparison.OrdinalIgnoreCase)).FirstOrDefault() ?? defaultSite;
}

```

After digging around, the error occurs here (_app.AppConfig.RedirectUri, contains the initialized url)
`var authenticationResult = await _app.AcquireTokenByAuthorizationCode(_azureOptions.GetGraphScopes, code).ExecuteAsync();`

[10:38:12 ERR] An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> Microsoft.Identity.Client.MsalServiceException: AADSTS500112: The reply address 'https://abc.site.com/signin-oidc' does not match the reply address 'https://abc1.site.com/signin-oidc' provided when requesting Authorization code.
Trace ID: 4fa8fa69-bd5a-494e-bd09-5f51f1432c00
Correlation ID: 82d2eea1-e201-4cb3-9b0c-a4921da48c87
Timestamp: 2019-06-16 14:38:12Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateErrorResponse(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendHttpMessageAsync(OAuth2Client client, String tokenEndpoint)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.AuthorizationCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByAuthorizationCodeParameters authorizationCodeParameters, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Authentication.AzureAdAuthenticationBuilderExtensions.ConfigureAzureOptions.<Configure>b__5_1(AuthorizationCodeReceivedContext context) in C:\Users\xxx\source\Workspaces\xx\xx\TemplateExtensions\AzureAdAuthenticationBuilderExtensions.cs:line 143
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthorizationCodeReceivedEventAsync(OpenIdConnectMessage authorizationResponse, ClaimsPrincipal user, AuthenticationProperties properties, JwtSecurityToken jwt)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
[10:38:12 INF] Request finished in 229.4081ms 404

**Comment by MarkZuber** [comment]
You're OIDC configuration within asp.net core is requesting the authorization code using https://abc1.site.com and then you're trying to redeem that authorization code with MSAL providing a redirect uri of https://abc.site.com.  This is not allowed.

**Comment by zulander1** [comment]
@MarkZuber: So, if the configuration at startup is https://abc1.site.com/ (which means that the uri is cached). Then it means that i cannot change the URI dynamically.   Can you think of a workaround or a alternative way of doing it ?

My senario :

DNS load balancer: https://abc.site.com (x.x.x.100, x.x.x.101,x.x.x.103)
 
Server1 (ip: x.x.x.100) - listening to 
       ---  https://abc.site.com/
       ---  https://abc1.site.com/

Server2  (ip: x.x.x.101) - listening to 
       ---  https://abc.site.com/
       ---  https://abc2.site.com/

Server3  (ip: x.x.x.102) - listening to 
       ---  https://abc.site.com/
       ---  https://abc3.site.com/

If the server1 fails then the server2 will take over  and so on... let say the server 3 have a new/old version then the server2 and 1. So how would i get access to the server3 ? This also mean that if we connect to server3 (https://abc3.site.com). It will stop responding to https://abc.site.com which is not good !

**Comment by MarkZuber** [comment]
Are abc1, abc2, and abc3 actual customer-visible sites (like foo.microsoft.com and bar.microsoft.com) that have different meaning?  Or are these just aliases for the individual boxes behind the load balancer and abc is the only site that matters (e.g. www.microsoft.com)?  

If it's the former, then I'm not sure why you have a load balancer for this configuration since you're effectively exposing three sites.  If it's the latter, then you should always use abc.site.com as your redirect URI and be storing your tokens into a distributed cache so that any site behind the load balancer can access them.

**Comment by zulander1** [comment]
The abc1, abc2, and abc3 as not customer-visible sites, only abc is.  Currently everything works.. However, sometimes we need to access  individually (Server3 (https://abc3.site.com/)) for x reason.. this is not working...

**Comment by MarkZuber** [comment]
This is by design since you can't use a different redirect for auth code versus retrieval.  "Fixing" this would break security validations.  Glad to hear the front line case is working as it should for abc.site.com.

**Comment by zulander1** [comment]
Can we override the check?
