### ISSUE TITLE
AcquireTokenForClient throws Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0 in .Net Core ASP .Net Web API

### ISSUE THREAD

**Issue by venkatesh-bhupathi** [AzureAD/microsoft-authentication-library-for-dotnet#1258]
We have a **.Net Core 2.0 based Web API**, we are using Microsoft.Identity.Client version 4.1.0 to get the token based on Certificate credential. Following is the code,

IConfidentialClientApplication app;
Microsoft.Identity.Client.AuthenticationResult output;
var cert = GetCert();

app = ConfidentialClientApplicationBuilder.Create(clientId)
          .WithTenantId("Microsoft Tenant ID")
          .WithCertificate(cert)
          .Build();
           var scopes = new string[] { scope };
try
{
   output = await app.**AcquireTokenForClient**(scopes).ExecuteAsync().ConfigureAwait(false);
}

This call **AcquireTokenForClient** throws the following exception,

**Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b77a5c561934e089'.":"System.Security.Cryptography.SHA256Cng

   at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendCertificate)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialHelper.CreateClientCredentialBodyParameters(ICoreLogger logger, ICryptographyManager cryptographyManager, ClientCredentialWrapper clientCredential, String clientId, AuthorityEndpoints endpoints, Boolean sendX5C)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)

We have another **Full Framework Web API which is targeting 4.6.1** in which this call works fine without any issue.

**Comment by venkatesh-bhupathi** [comment]
@jmprieur Could you please help us with this issue in getting access token based on certificate credentials in .Net core 2.0. This is blocking our deployment, would like to understand if there is a fix for this issue or do we need to convert the API to full framework from .Net core.

**Comment by henrik-me** [comment]
May be related to: https://github.com/dotnet/corefx/pull/18689 however seems from the stack trace that some net45 stuff is loading when we are running netcore. @bgavrilMS or @MarkZuber  something you can take a look at?

**Comment by henrik-me** [comment]
@venkatesh-bhupathi : can you pls. share additional details on the dotnet core version? Also can you pls. attach [logging](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging) and provide the additional details from the logs? (please ensure to remove PII)

**Comment by venkatesh-bhupathi** [comment]
Following are the dependency details from the API project,

`
TargetFramework - **netcoreapp2.0**

"Microsoft.AspNet.Cors  Version="5.2.4" 
"Microsoft.AspNetCore.All" Version="2.0.0"
"Microsoft.AspNetCore.Http.Features" Version="2.0.2"
"Microsoft.AspNetCore.Mvc.Versioning" Version="2.2.0"
"Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="2.2.0"
"Microsoft.Data.Services.Client" Version="5.8.3"
"Microsoft.IdentityModel.Authorization" Version="4.7.4978"
"Microsoft.IdentityModel.Clients.ActiveDirectory" Version="4.5.0"
`

Following are the logs from the MSAL Logging delegate,

`
[0]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:32:39 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) MSAL MSAL.Desktop with assembly version '4.1.0.0'. CorrelationId(68e881c5-0f87-49af-a82e-6c4a8dc65fe8)"
[1]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:32:49 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) === AcquireTokenForClientParameters ===\r\nSendX5C: False\r\nForceRefresh: False\r\n"
[2]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:32:50 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) \r\n=== Request Data ===\r\nAuthority Provided? - True\r\nScopes - [Scoped removed for sharing]\r\nExtra Query Params Keys (space separated) - \r\n"
[3]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:32:52 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) === Token Acquisition (ClientCredentialRequest) started:\n\tCache Provided: True\n\tAuthority Host: login.microsoftonline.com"
[4]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:32:53 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) Looking up access token in the cache."
[5]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:32:54 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) No matching entry found for user or assertion"
[6]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:33:08 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) Resolving authority endpoints... Already resolved? - FALSE"
[7]: "MSAL Info False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:33:13 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) Client Assertion does not exist or near expiry. "
[8]: "MSAL Error False (False) MSAL 4.1.0.0 MSAL.Desktop Microsoft Windows NT 6.2.9200.0 [07/10/2019 05:33:14 - 68e881c5-0f87-49af-a82e-6c4a8dc65fe8] (UnknownClient: 0.0.0.0) Exception type: System.TypeLoadException\r\n\r\n   at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)\r\n   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendCertificate)\r\n   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialHelper.CreateClientCredentialBodyParameters(ICoreLogger logger, ICryptographyManager cryptographyManager, ClientCredentialWrapper clientCredential, String clientId, AuthorityEndpoints endpoints, Boolean sendX5C)\r\n   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Internal.Requests.ClientCrede
ntialRequest.ExecuteAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)"
`

**Comment by jmprieur** [comment]
@venkatesh-bhupathi : apprently the MSAL.NET logs don't to indicate that this is a  .Net Core 2.0 Web API, This seems to be a .NET Framework one.
Would you have repro steps to share ? We have an ASP.NET Core 2.0 Web API sample you might want to start from? https://aka.ms/msidentity-aspnetcore-webapi-calls-msgraph ?

**Comment by venkatesh-bhupathi** [comment]
Thanks for your insight here @jmprieur, the Core API is referencing a Full Framework assembly which uses MSAL to fetch the token. We have moved the token resolver component to a Net Standard assembly, then Core API started working fine.

**Comment by jmprieur** [comment]
Thanks for the update, @venkatesh-bhupathi 
Do you want to close the issue?

**Comment by ashinzekene** [comment]
Having the same error on a .NET Framework app
```
Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.. Exception Stack trace:    
  at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendX5C)
   at Microsoft.Identity.Client.Internal.ClientCredentialWrapper.AddConfidentialClientParameters(OAuth2Client oAuth2Client, ICoreLogger logger, ICryptographyManager cryptographyManager, String clientId, Authority authority, Boolean sendX5C)
   at Microsoft.Identity.Client.OAuth2.TokenClient.AddBodyParamsAndHeaders(IDictionary`2 additionalBodyParameters, String scopes)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
 
```
