### ISSUE TITLE
[Bug] Build failed on Azure DevOps platform for Xamarin Forms Android App

### ISSUE THREAD

**Issue by maugerc** [AzureAD/microsoft-authentication-library-for-dotnet#1514]
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client v4.7.0

**Platform**
Xamarin Forms v3.6.0.344457

**What authentication flow has the issue?**
Azure Active Directory Authentification with AcquireTokenSilent

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL

**Repro**
Build Xamarin Forms Android App on Azure DevOps Pipeline

**Additional context/ Logs / Screenshots**
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Stack`1' (defined in assembly 'Microsoft.Identity.Client, Version=4.7.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae') with scope 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.Stack`1
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by jmprieur** [comment]
@maugerc 
I got the same issue in the CI build of the xamarin sample

You might want to add a build action in Azure DevOps to install the .NET Core 3.0.100 framework
![image](https://user-images.githubusercontent.com/13203188/69443398-94022480-0d4e-11ea-8a3f-1e5a4eb23d52.png)

**Comment by maugerc** [comment]
Ok, thanks for reply, but I must migrate App project to NET Standard 2.1 and Android project to 10.0 for compatibility with NET Core 3.0. It's too much changes for prod app, but thanks for answer.

**Comment by tjagdaledminc** [comment]
May i know what fixes we have done to close this issue?
Thanks

**Comment by maugerc** [comment]
> May i know what fixes we have done to close this issue?
> Thanks

Hi, I rollback MSAL version to previous. I think with the .NET Standard 2.1+ and Android 10+ the MSAL new version work fine, I don't tried.

**Comment by solankivinay4u** [comment]
@tjagdaledminc @maugerc I can build in local machine with old version. In order to work in Azure pipeline, I have update packages for Android and it works fine. Additionaly I have to add Dotnet core as suggested by @jmattheus in pipeline.
Thanks for all support guys!!
