### ISSUE TITLE
[Bug] IOException: The process cannot access the file '%appdata%\.IdentityService\msal.cache.lockfile' be cause it is being used by another process

### ISSUE THREAD

**Issue by bganapa** [AzureAD/microsoft-authentication-library-for-dotnet#1673]
**Which Version of MSAL are you using ?**
4.8.1.0

**Platform**
net45

**What authentication flow has the issue?**

    * [ ] Username Password
 
Other? - please describe;

**Is this a new or existing app?**
The app is in preview/private module version

**Issue**
While running our automation with the Az.Accounts powershell module , we hit the following issue. We do not have any tests running in parallel.  Its a simple flow of login and selecting a subscription. We do not have a consistent repro.

2020-03-02 10:44:03.1051 [EXCEPTION] System.InvalidOperationException: Could not get access to the shared lock file. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Administrator\AppData\Local\.IdentityService\msal.cache.lockfile' be
cause it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boo
lean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.Identity.Client.Extensions.Msal.CrossPlatLock..ctor(String lockfilePath, Int32 lockFileRetryDelay, Int32 lockFileRetryCount)
   --- End of inner exception stack trace ---
   at Microsoft.Identity.Client.Extensions.Msal.CrossPlatLock..ctor(String lockfilePath, Int32 lockFileRetryDelay, Int32 lockFileRetryCount)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateCrossPlatLock(StorageCreationProperties storageCreationProperties)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.RegisterCache(ITokenCache tokenCache)
   at Microsoft.Azure.Commands.Common.Authentication.Authentication.Clients.AuthenticationClientFactory.CreatePublicClient(String clientId, String tenantId, String authority, String redirectUri, Boolean useAdfs)
   at Microsoft.Azure.Commands.Common.Authentication.Authentication.Clients.AuthenticationClientFactory.ListAccounts(String authority)
   at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.RefreshContextsFromCache()
   at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.get_DefaultContext()
   at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext()
   at Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()

**Comment by bgavrilMS** [comment]
I will investigate

**Comment by bgavrilMS** [comment]
Is this [PowerShell 7 RC 3](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0-rc.3)  ?

**Comment by bgavrilMS** [comment]
I can see a lock being acquired but it should also be released pretty quickly. A few questions: 

- Is the lock file ever deleted? 
- Inside the lock file there is a process ID of the process which holds the lock. Can you observe what is happening with this process?
- Have you defined your own values for LockRetryDelay and LockRetryCount? They default to 100ms delay with 600 retries.
- Can you give me logs the extension creates?

**Comment by TheOnlyWei** [comment]
Some extra information since I produced the bug initially:

- The lock file flickered in and out of existence as if it was being deleted and created every half second.
- The bug was first encountered when I ran the Powershell Canary.Tests.ps1 and Powershell CTQ Workloads.Tests.PS.ps1 at the same time, so there is probably a deadlock or race condition. Although I cancelled both test then just ran the Powershell CTQ after and still got that error.

**Comment by bgavrilMS** [comment]
It's normal for the lock file to get created and deleted quickly - since acquiring the lock means creating the file and releasing the lock means deleting the file. 

I would expect the lock file to be invoked 2 or 3 times ( I need to see your code to be sure):

- once when you register the token cache via `MsalCacheHelper.RegisterCache`
- once when you get a token from AAD and we persist it

It would be great if we could isolate a repro.

**Comment by henrik-me** [comment]
Fixed in extensions
