### ISSUE TITLE
[Bug] AuthenticationException: Code: generalException when attempting to authenticate and make calls to Graph APIs within a simple console app on an Azure VM.

### ISSUE THREAD

**Issue by Debro012** [AzureAD/microsoft-authentication-library-for-dotnet#1747]
**Which Version of MSAL are you using ?**
Note that to get help, you need to run the latest version. Preview version are also ok. 
For ADAL, please log issues to https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

**4.11.0**

**Platform**

**.Net Core 2.1**

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

Client Credentials

**Is this a new or existing app?**

This is a new app or experiment

**Repro**

```csharp
class Program
    {
        static async Task Main(string[] args)
        {

            IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create("clientId")
                .WithTenantId("tenantId")
                .WithClientSecret("clientSecret")
                .Build();

            ClientCredentialProvider clientCredentialProvider = new ClientCredentialProvider(confidentialClientApplication);
            GraphServiceClient graphServiceClient = new GraphServiceClient(clientCredentialProvider);

            var user = await graphServiceClient.Users
                .Request()
                .Filter($"employeeId eq '12345'")
                .GetAsync();
   
            Console.WriteLine($"The name of the user from Graph is {user[0].GivenName}");
          
        }
    }
```

**Expected behavior**
Simply write the GivenName of the user to the console.

**Actual behavior**
Microsoft.Graph.ServiceException
  HResult=0x80131500
  Message=Code: generalException
Message: An error occurred sending the request.

  Source=Microsoft.Graph.Core
  StackTrace:
   at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at Microsoft.Graph.GraphServiceUsersCollectionRequest.<GetAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 376
   at TestGraphCallsConsoleApp.Program.<GetUser>d__1.MoveNext() in C:\Users\srvap136448dev\source\repos\TestGraphCallsConsoleApp\TestGraphCallsConsoleApp\Program.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 376
   at TestGraphCallsConsoleApp.Program.<Main>d__0.MoveNext() in C:\Users\srvap136448dev\source\repos\TestGraphCallsConsoleApp\TestGraphCallsConsoleApp\Program.cs:line 17
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\791\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at TestGraphCallsConsoleApp.Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    System.Net.Http.HttpClient.HandleFinishSendAsyncError(System.Exception, System.Threading.CancellationTokenSource) in HttpClient.cs
    System.Net.Http.HttpClient.FinishSendAsyncBuffered(System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>, System.Net.Http.HttpRequestMessage, System.Threading.CancellationTokenSource, bool) in HttpClient.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync(System.Uri, System.Collections.Generic.IDictionary<string, string>, System.Net.Http.HttpContent, System.Net.Http.HttpMethod)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    Microsoft.Identity.Client.Http.HttpManager.ExecuteWithRetryAsync(System.Uri, System.Collections.Generic.IDictionary<string, string>, System.Net.Http.HttpContent, System.Net.Http.HttpMethod, Microsoft.Identity.Client.Core.ICoreLogger, bool, bool)
    ...
    [Call Stack Truncated]

Inner Exception 1:
AuthenticationException: Code: generalException
Message: Unexpected exception occured while authenticating the request.

Inner Exception 2:
OperationCanceledException: The operation was canceled.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Add any other context about the problem here, such as logs and screebshots. Logging is described at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging

**Comment by bgavrilMS** [comment]
1. I assume you used actual values for "clientID", "tenantID" and "clientSecret" ?
2. We do not own the Graph SDK. Could you provide a repro for the MSAL client only please? Or log the bug on the Graph SDK folks. 

if instead of creating the graph object you just call and this fails, it's a problem of MSAL's

```csharp
confidentialClientApplication.AcquireTokenForClient(<scopes>)
```

Otherwise, it's a graph problem: https://github.com/microsoftgraph/msgraph-sdk-dotnet

**Comment by Debro012** [comment]
> 1. I assume you used actual values for "clientID", "tenantID" and "clientSecret" ?
> 2. We do not own the Graph SDK. Could you provide a repro for the MSAL client only please? Or log the bug on the Graph SDK folks.
> 
> if instead of creating the graph object you just call and this fails, it's a problem of MSAL's
> 
> ```cs
> confidentialClientApplication.AcquireTokenForClient(<scopes>)
> ```
> 
> Otherwise, it's a graph problem: https://github.com/microsoftgraph/msgraph-sdk-dotnet

Thank you @bgavrilMS . Upon further research I have discovered the issue is in relation to proxy config. I am will need to build an understanding on IMsalHttpClientFactory, for I can utilize an HttpClient configured to go through the proxy. However, I have opened the following request, for no detailed examples are available for reference: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1751

Otherwise, it would be great to know how to set up the proxy for all http/https calls within the .Net Core 2.1 app.

**Comment by bgavrilMS** [comment]
Sounds good, let's follow up the discussion on the documentation issue you've opened.
