### ISSUE TITLE
question about possible bug in earlier MSAL release

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#1833]
With an MSAL 4.11 built app we experienced problems with getting a token on one device.
I have added app log fragments below. 
We log an MS Authenticator version. 6.2004.2575, where later on MSAL does not get an account and fails with some debug info stating that there is no broker installed.
Does this look like a bug that has been solved in MSAL 4.13?

2020-05-16 19:07:22.3996 Debug 1    LogWrapper.MinimalLogLevel change: Off => Debug
2020-05-16 19:07:22.4664 Info  1    ** Application MijnTeam, version 3.0.0.21 is initialized. **
2020-05-16 19:07:23.1865 Debug 1    Startup: supported: Tls12
2020-05-16 19:07:23.3047 Info  1    com.azure.authenticator - version 6.2004.2757
2020-05-16 19:07:23.4189 Debug 1    SigmaxApplication.OnActivityStarted(SplashActivity)
2020-05-16 19:07:23.4217 Debug 1    BackgroundService.Stop()

020-05-16 19:07:24.2660 Info  4    Init progres : Controleren op geldige inlog 6 %
2020-05-16 19:07:24.2669 Debug 4    LaadschermViewModel.StartupServicesAsync(): LoginSilentAsync()
2020-05-16 19:07:24.2723 Info  4    Account.LoginSilentAsync(): initiate SilentTokenRequest >>
2020-05-16 19:07:24.2774 Info  4    Account.LoginSilentAsync(RoleCount 1): initiate SilentTokenRequest
2020-05-16 19:07:24.2821 Info  4    Account.LoginServiceBase.Execute()
2020-05-16 19:07:24.2880 Info  4    Account.LoginServiceBase.Execute() create new login task Silent
2020-05-16 19:07:24.2896 Info  4    Account.LoginServiceBase.Execute() Start login task Silent
2020-05-16 19:07:24.3124 Debug 6    Account.GetTokenSilentAsync() >>
2020-05-16 19:07:24.4265 Debug 1    SigmaxApplication.OnActivityStopped(SplashActivity)
2020-05-16 19:07:24.6653 Info  6    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:24] (UnknownClient: 0.0.0.0) Looper.MainLooper returned: Looper (main, tid 2) {bb067fe}
2020-05-16 19:07:24.7462 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:24] (UnknownClient: 0.0.0.0) Using broker protocol version: 3.0
2020-05-16 19:07:24.7713 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:24] (UnknownClient: 0.0.0.0) Looper.MainLooper returned: Looper (main, tid 2) {bb067fe}
2020-05-16 19:07:25.4115 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25] (UnknownClient: 0.0.0.0) Found 1 accounts in the account manager.
2020-05-16 19:07:25.4233 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25 - ae741435-9275-4f54-bedc-109e23a2f55e] (UnknownClient: 0.0.0.0) MSAL MSAL.Xamarin.Android with assembly version '4.11.0.0'. CorrelationId(ae741435-9275-4f54-bedc-109e23a2f55e)
2020-05-16 19:07:25.4395 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25 - ae741435-9275-4f54-bedc-109e23a2f55e] (UnknownClient: 0.0.0.0) === OnBehalfOfParameters ===
LoginHint provided: False
User provided: True
ForceRefresh: False

2020-05-16 19:07:25.4688 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25 - ae741435-9275-4f54-bedc-109e23a2f55e] (UnknownClient: 0.0.0.0) 
=== Request Data ===
Authority Provided? - True
Scopes - api://WS20mijnteam-p.mobile-apps.ns.nl/.default offline_access
Extra Query Params Keys (space separated) - 

2020-05-16 19:07:25.4706 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25 - ae741435-9275-4f54-bedc-109e23a2f55e] (UnknownClient: 0.0.0.0) === Token Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
2020-05-16 19:07:25.4884 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25 - ae741435-9275-4f54-bedc-109e23a2f55e] (UnknownClient: 0.0.0.0) Can invoke broker. Will attempt to acquire token with broker. 
2020-05-16 19:07:25.5035 Info  7    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25] (UnknownClient: 0.0.0.0) Looper.MainLooper returned: Looper (main, tid 2) {bb067fe}
2020-05-16 19:07:25.5903 Info  4    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25] (UnknownClient: 0.0.0.0) Using broker protocol version: 3.0
2020-05-16 19:07:25.6079 Info  4    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25] (UnknownClient: 0.0.0.0) Looper.MainLooper returned: Looper (main, tid 2) {bb067fe}
2020-05-16 19:07:25.7355 Info  4    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:25] (UnknownClient: 0.0.0.0) Found broker account in Android account manager using the provided login hint.
2020-05-16 19:07:26.0194 Info  4    MSAL Info False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:07:26] (UnknownClient: 0.0.0.0) Looper.MainLooper returned: Looper (main, tid 2) {bb067fe}
2020-05-16 19:12:21.5883 Debug 1    BaseActivity.OnStop(MainAppActivity)
2020-05-16 19:12:21.5917 Debug 1    SigmaxApplication.OnActivityStopped(MainAppActivity)
2020-05-16 19:12:21.5937 Debug 1    BackgroundService.Start()
2020-05-16 19:12:21.5958 Debug 1    MijnTeamApplicationSpecification.OnSleep()
2020-05-16 19:12:33.4713 Error 6    MSAL Error False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:12:33] (UnknownClient: 0.0.0.0) Broker invocation failed.Exception type: Java.Lang.Exception

  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <6c3f16a59f2c4d1a988eaf4382590ffb>:0 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureInvoker.GetResult (System.Int64 timeout, Java.Util.Concurrent.TimeUnit unit) [0x0006d] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureExtensions+<>c__DisplayClass0_0.<GetResultAsync>b__0 () [0x00000] in <e0d2bda67743404299c282d07e246cf7>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <422b070e8e6f44de809d88c6b03c8240>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <422b070e8e6f44de809d88c6b03c8240>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.Identity.Client.Platforms.Android.AndroidBrokerHelper.GetBrokerAuthTokenSilentlyAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload, Android.App.Activity callerActivity) [0x000de] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenInternalAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x001ca] in <25567c044bdc4d38866335f9950e82f9>:0 
  --- End of managed Java.Lang.Exception stack trace ---
android.accounts.OperationCanceledException
	at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:2295)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2307)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2304)

2020-05-16 19:12:33.4777 Error 6    MSAL Error False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:12:33] (UnknownClient: 0.0.0.0) Android broker authentication failed.
2020-05-16 19:12:33.4797 Error 6    MSAL Error False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:12:33] (UnknownClient: 0.0.0.0) In order to perform brokered authentication on android you need to ensure that you have installed either Intune Company Portal (5.0.4689.0 or greater) or Microsoft Authenticator (6.2001.0140 or greater).
2020-05-16 19:12:33.5021 Error 6    MSAL Error False (False) MSAL 4.11.0.0 MSAL.Xamarin.Android 26 [05/16/2020 17:12:33 - ae741435-9275-4f54-bedc-109e23a2f55e] (UnknownClient: 0.0.0.0) Exception type: Microsoft.Identity.Client.MsalClientException
, ErrorCode: android_broker_operation_failed
---> Inner Exception Details
Exception type: Java.Lang.Exception

  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <6c3f16a59f2c4d1a988eaf4382590ffb>:0 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureInvoker.GetResult (System.Int64 timeout, Java.Util.Concurrent.TimeUnit unit) [0x0006d] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureExtensions+<>c__DisplayClass0_0.<GetResultAsync>b__0 () [0x00000] in <e0d2bda67743404299c282d07e246cf7>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <422b070e8e6f44de809d88c6b03c8240>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <422b070e8e6f44de809d88c6b03c8240>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.Identity.Client.Platforms.Android.AndroidBrokerHelper.GetBrokerAuthTokenSilentlyAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload, Android.App.Activity callerActivity) [0x000de] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenInternalAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x0034f] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload) [0x00091] in <25567c044bdc4d38866335f9950e82f9>:0 
  --- End of managed Java.Lang.Exception stack trace ---
android.accounts.OperationCanceledException
	at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:2295)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2307)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2304)

=== End of inner exception stack trace ===

  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.HandleBrokerOperationError (System.Exception ex) [0x0002b] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload) [0x000ac] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Broker.BrokerSilentRequest.SendAndVerifyResponseAsync () [0x00080] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Broker.BrokerSilentRequest.SendTokenRequestToBrokerAsync () [0x000a3] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Requests.SilentRequest.ExecuteBrokerAsync (System.Threading.CancellationToken cancellationToken) [0x00098] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Requests.SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x000d9] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x0017e] in <25567c044bdc4d38866335f9950e82f9>:0 
2020-05-16 19:12:33.6051 Fatal 6    Account.GetAdTokenSilent(): Exception Kan niet inloggen - MSAL.Xamarin.Android.4.11.0.0.MsalClientException: 
	ErrorCode: android_broker_operation_failed
Microsoft.Identity.Client.MsalClientException: Exception of type 'Java.Lang.Exception' was thrown. ---> Java.Lang.Exception: Exception of type 'Java.Lang.Exception' was thrown.
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <6c3f16a59f2c4d1a988eaf4382590ffb>:0 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureInvoker.GetResult (System.Int64 timeout, Java.Util.Concurrent.TimeUnit unit) [0x0006d] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureExtensions+<>c__DisplayClass0_0.<GetResultAsync>b__0 () [0x00000] in <e0d2bda67743404299c282d07e246cf7>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <422b070e8e6f44de809d88c6b03c8240>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <422b070e8e6f44de809d88c6b03c8240>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.Identity.Client.Platforms.Android.AndroidBrokerHelper.GetBrokerAuthTokenSilentlyAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload, Android.App.Activity callerActivity) [0x000de] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenInternalAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x0034f] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload) [0x00091] in <25567c044bdc4d38866335f9950e82f9>:0 
   --- End of inner exception stack trace ---
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.HandleBrokerOperationError (System.Exception ex) [0x0002b] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload) [0x000ac] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Broker.BrokerSilentRequest.SendAndVerifyResponseAsync () [0x00080] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Broker.BrokerSilentRequest.SendTokenRequestToBrokerAsync () [0x000a3] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Requests.SilentRequest.ExecuteBrokerAsync (System.Threading.CancellationToken cancellationToken) [0x00098] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Requests.SilentRequest.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x000d9] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync (System.Threading.CancellationToken cancellationToken) [0x001ed] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync (Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenCommonParameters commonParameters, Microsoft.Identity.Client.ApiConfig.Parameters.AcquireTokenSilentParameters silentParameters, System.Threading.CancellationToken cancellationToken) [0x000cd] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Ns.Knip.Mobile.Account.AdTokenService.GetAdTokenSilent (System.Object context) [0x00137] in <6e8752381c224212930456fcc158e136>:0 
Inner Excception: Java.Lang.Exception: Exception of type 'Java.Lang.Exception' was thrown.
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <6c3f16a59f2c4d1a988eaf4382590ffb>:0 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureInvoker.GetResult (System.Int64 timeout, Java.Util.Concurrent.TimeUnit unit) [0x0006d] in <e0d2bda67743404299c282d07e246cf7>:0 
  at Android.Accounts.IAccountManagerFutureExtensions+<>c__DisplayClass0_0.<GetResultAsync>b__0 () [0x00000] in <e0d2bda67743404299c282d07e246cf7>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <422b070e8e6f44de809d88c6b03c8240>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <422b070e8e6f44de809d88c6b03c8240>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.Identity.Client.Platforms.Android.AndroidBrokerHelper.GetBrokerAuthTokenSilentlyAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload, Android.App.Activity callerActivity) [0x000de] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenInternalAsync (System.Collections.Generic.IDictionary`2[TKey,TValue] brokerPayload) [0x0034f] in <25567c044bdc4d38866335f9950e82f9>:0 
  at Microsoft.Identity.Client.Platforms.Android.AndroidBroker.AcquireTokenUsingBrokerAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] brokerPayload) [0x00091] in <25567c044bdc4d38866335f9950e82f9>:0 
  --- End of managed Java.Lang.Exception stack trace ---
android.accounts.OperationCanceledException
	at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:2295)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2307)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2304)

2020-05-16 19:12:33.6074 Debug 6    Account.GetTokenSilentAsync() <<
2020-05-16 19:12:33.6396 Warn  5    Account.ConvertToLoginResult(RoleCount 1): Silent  token did not meet requirements: Failed
2020-05-16 19:12:33.6432 Info  5    Account.LoginSilentAsync(): duration: 302031,9361 ms

**Comment by jennyf19** [comment]
@trwalke can you please answer this? thx.

**Comment by trwalke** [comment]
I dont think this was fixed in 4.14 but i recommend updating regardless. looks like a strange communication error with the broker. The odd thing here is that the broker is responding with the accounts in the cache but when you go to use that same account things crash. I don't really see the exact error message here though, can you try debugging into this and grabbing the error message if there is one? These logs have error codes but they dont provide enough detail to explain what is really happening here

**Comment by trwalke** [comment]
Please reopen if this fix is still needed
