### ISSUE TITLE
[Bug] NullReferenceException when calling Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.GetCryptoProviderForSha256 in .NET 4.7.2

### ISSUE THREAD

**Issue by tawlin** [AzureAD/microsoft-authentication-library-for-dotnet#1892]
**Which Version of MSAL are you using ?**
Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.19.0.0

**Platform**
net472

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Integrated Windows Auth

**Is this a new or existing app?**
a. The app is in production, and I have upgraded from .NET 4.5 to .NET 4.7.2

**Repro**

```csharp
X509Certificate2 certificate = FindSecretsUpdaterAuthCertByCertName(keyVaultAuthCertName);  
ClientAssertionCertificate assertionCert = new ClientAssertionCertificate(_keyVaultAdAppClientId, certificate);  

KeyVaultClient.AuthenticationCallback authenticationCallback = new KeyVaultClient.AuthenticationCallback(  
                (authority, resource, scope) => GetAccessTokenAsync(  
                                authority,  
                                resource,  
                                scope,  
                                assertionCert));  

_httpClient = new HttpClient();  
_keyVaultClient = new KeyVaultClient(authenticationCallback, _httpClient);  

private async Task<string> GetAccessTokenAsync(string authority, string resource, string scope, ClientAssertionCertificate assertionCert)  
{  
                AuthenticationContext context = new AuthenticationContext(authority, TokenCache.DefaultShared);  
                AuthenticationResult result = await context.AcquireTokenAsync(resource, assertionCert);  

                return result.AccessToken;  
}
```

**Expected behavior**
Get access token by using client assertion cert to talk to Azure KeyVault.

**Actual behavior**
NullReferenceException is thrown when trying to get access token.

**Possible Solution**

**Additional context/ Logs / Screenshots**
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.GetCryptoProviderForSha256(RSACryptoServiceProvider rsaProvider)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 x509Certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(ClientAssertionCertificate credential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.AddClientKey(ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__1d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at xxxx.<GetAccessTokenAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by bgavrilMS** [comment]
That is a very old (~5 years) version of ADAL that we no longer maintain. The bug has probably been fixed in subsequent releases. Please upgrade you identity library, preferably to MSAL (ADAL is on a deprecation path). I believe it's easier to upgrade from ADAL v2 to MSAL.
