### ISSUE TITLE
SHA256Cng breaks Core code

### ISSUE THREAD

**Issue by PeterWone** [AzureAD/microsoft-authentication-library-for-dotnet#1937]
**Preamble**
After forking your repo to have a go at fixing it myself, I discovered that you have a NetCoreCryptographyManager which means you have some awareness of the problem. Now I'm unsure whether this is a broken version of identity, or something is causing the wrong version of Connect-ExchangeOnline to be loaded. I'm investigating that at the moment so it's entirely possible I will delete this issue myself. I'll keep you posted.

**I can achieve the same thing indirectly using `Import-PSSession` which implies there's nothing wrong with your library, which in turn implies that the reported problems are probably like mine and caused by the powershell loading the wrong version of a cmdlet. On that basis I'm going to kill this issue before it wastes your time.**

**Which Version of MSAL are you using ?**
It doesn't matter

**Platform**
netcore

**What authentication flow has the issue?**
Everything that involves a client that tries to use `SHA256Cng`

Other? - please describe;

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**
Build a netcore app and call something that depends on this library. 

I hosted PowerShell in a C# console app and tried to run this

```powershell
param([string] $username,[string] $password)

$secstr = New-Object -TypeName System.Security.SecureString
$password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
$cred = New-Object -Typename System.Management.Automation.PSCredential -ArgumentList $username, $secstr

Connect-ExchangeOnline -Credential $cred
Get-OutboundConnector
Disconnect-ExchangeOnline -Confirm:$false
```

**Expected behavior**
I expect authentication, a result from `Get-OutboundConnector`, and disconnection.

**Actual behavior**
`Connect-ExchangeOnline` barfs because it uses this library which tries to use SHA256Cng, which is not present in netcore. The stack trace is in the Additional context section.

**Possible Solution**
Replace all your references to SHA256Cng with SHA256 instead. It really doesn't matter that it's slower. Authentication is not something you normally do in a loop. Or use an exception handler that uses SHA256 when the attempt to use SHA256Cng fails..

You should probably also fix references to SHA384Cng and similar, since none of the Cng versions are present in netcore.

**Additional context/ Logs / Screenshots**
```
An unhandled exception of type 'System.Management.Automation.RuntimeException' occurred in System.Management.Automation.dll: 'Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.. '
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.TypeLoadException : Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.CreateSha256Hash(String input)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.LogReturnedToken(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.PostRunAsync(AuthenticationResult result)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext()
```

**Comment by bgavrilMS** [comment]
Hi Peter, this is the MSAL repository. ADAL has been deprecated and we will not fix this sort of bug there. There is at least 1 known issue with CNG certs in MSAL, but as far as I know it does not affect .net core

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1726

The issue also shows a workaround. Hope this helps.
