### ISSUE TITLE
[Bug] AcquireTokenByIntegratedWindowsAuth + ADFS returns parse error

### ISSUE THREAD

**Issue by TiagoBrenck** [AzureAD/microsoft-authentication-library-for-dotnet#1994]
**Which Version of MSAL are you using ?**
MSAL 4.17.1

**Platform**
net 4.7.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;
This is inside an ADFS environment

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**
On an ADFS environment VM, run the code:

```csharp
        public MainWindow()
        {
            InitializeComponent();

            try
            {
                string clientId = "6a4c2f4c-1d1a-4e0c-959e-4ba1be2205c4";
                var publicClientApp = PublicClientApplicationBuilder.Create(clientId)
                    .WithAdfsAuthority("https://sts.cxpaadtenant.com/adfs")
                    .Build();

                var result = publicClientApp.AcquireTokenByIntegratedWindowsAuth(new string[] { "user_impersonation" })
                    .ExecuteAsync().GetAwaiter().GetResult();
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                throw;
            }
            
            
        }
```

**Expected behavior**
Acquire the access token with `user_impersonation` scope

**Actual behavior**
Error: `Unexpected character encountered while parsing value: <. Path '', line 1, position 1.`

**Possible Solution**

**Additional context/ Logs / Screenshots**
```
   at Microsoft.Identity.Json.JsonTextReader.ParseValue()
   at Microsoft.Identity.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Microsoft.Identity.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Microsoft.Identity.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Identity.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Microsoft.Identity.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Identity.Client.Utils.JsonHelper.DeserializeFromJson[T](String json)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<GetTokenAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendHttpAndClearTelemetryAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendTokenRequestAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<ExecuteAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ClientApp.MainWindow..ctor() in C:\Users\LabAdmin\Desktop\1-4-Setup-IWA-Playground\ClientApp\MainWindow.xaml.cs:line 42
```

**Comment by bgavrilMS** [comment]
Thanks @TiagoBrenck . MSAL does not support this flow for ADFS authority, but it should throw a nice exception (also for B2C authority)

**Comment by TiagoBrenck** [comment]
FYI @kalyankrishna1 

Thanks @bgavrilMS

**Comment by henrik-me** [comment]
By design

**Comment by pseabury** [comment]
Why is this flow not supported in ADFS Authority?  What is the recommended alternative for users federated via ADFS?
