### ISSUE TITLE
[Bug] Throw a better exception when ROPC is attempted with MSA account

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#2169]
**Which Version of MSAL are you using ?**
4.22

Attempt ROPC, with authority correctly set to `l.m.o/organizations`. Provide an MSA username to the API.

**Expected** an exception explaining the root cause. 

Implementation suggestion: 

- We could use either the "domain_name" from the userrealm call  (need to confirm with MSA folks)
![image](https://user-images.githubusercontent.com/12273384/98519172-4ab12a80-2268-11eb-923d-a3c7052fdeb5.png)

- Or the fact that the subsequent call to `GET /FederationMetadata/2007-06/FederationMetadata.xml HTTP/1.1` fails with 406 Not Acceptable. 

**Actual** a bad exception which causes developers to think there is a bug in MSAL

---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Identity.Client.WsTrust.MexDocument.SetPolicyEndpointAddresses(XContainer mexDocument)
   at Microsoft.Identity.Client.WsTrust.MexDocument..ctor(String responseBody)
   at Microsoft.Identity.Client.WsTrust.WsTrustWebRequestManager.GetMexDocumentAsync(String federationMetadataUrl, RequestContext requestContext)
   at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.PerformWsTrustMexExchangeAsync(String federationMetadataUrl, String cloudAudienceUrn, UserAuthType userAuthType, String username, SecureString password)
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.FetchAssertionFromWsTrustAsync()
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByUsernamePasswordParameters usernamePasswordParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenByUsernamePasswordAsync(String[] scopes, String username, SecureString password, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.UsernamePasswordCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

**Comment by jennyf19** [comment]
> Implementation suggestion:
> 1. We could use either the "domain_name" from the userrealm call (need to confirm with MSA folks)
> 2. Or the fact that the subsequent call to GET /FederationMetadata/2007-06/FederationMetadata.xml HTTP/1.1 fails with 406 Not Acceptable.

I would lean towards (1), as it doesn't make sense to continue if we know it's going to fail. I'll sync w/msa tomorrow (11.25) to ask about this.

**Comment by bgavrilMS** [comment]
Yeah, I think approach 1 is cleaner.

**Comment by neha-bhargava** [comment]
Fixed in [Msal release 4.24.0](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.24.0)

**Comment by rayluo** [comment]
> Implementation suggestion:
> 1. We could use either the "domain_name" from the userrealm call (need to confirm with MSA folks)
> 2. Or the fact that the subsequent call to GET /FederationMetadata/2007-06/FederationMetadata.xml HTTP/1.1 fails with 406 Not Acceptable.

FWIW, I tested this with MSAL Python just now, and approach (2) would not fail with "406 Not Acceptable", but its response would contain no wstrust endpoint for further interaction. So, we ended up using an "approach (3): if no wstrust endpoint was available, we emit an actionable error message". Of course, approach (1) is also viable.

**Comment by jennyf19** [comment]
@rayluo that's interesting because we do get the 406 error. We went w/option 1 based on conversation w/ests. will loop you in on the email.
