### ISSUE TITLE
50058 Azure AD errors

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-dotnet#2176]
We get a lot of Azure AD Sign-in error code 50058 responses when doing silent logins from MSAL based Xamarin apps on Android.
We use brokered login with MS Authenticator. We don't expect the 50058 in most cases.  I read various explanations on internet but can this also be caused by misconfiguration or wrong use of MSAL library?

**Comment by bgavrilMS** [comment]
Hi @harmjonker - could you give us more details please? What flow gives you this 50058 error? What is 50058? Is it an error code from an MSAL exception?

**Comment by harmjonker** [comment]
![issue interrupted login](https://user-images.githubusercontent.com/55669455/98690509-4de20e80-236d-11eb-944c-04b27c205092.png)
![issue interrupted login 2](https://user-images.githubusercontent.com/55669455/98690511-4e7aa500-236d-11eb-8031-6e0d9bcfdf91.png)

**Comment by harmjonker** [comment]
Error Code | 50058
-- | --
Message | Session information is not sufficient for single-sign-on.
Remediation | This means that a user is not signed in. This is a common error that's expected when a user is unauthenticated and has not yet signed in. If this error is encountered in an SSO context where the user has previously signed in, this means that the SSO session  was either not found or invalid. This error may be returned to the application if prompt=none is specified.

**Comment by harmjonker** [comment]
We expect this not to happen for every individual app again.

**Comment by bgavrilMS** [comment]
I've never seen this error. It looks to be related to the browser, not to the broker - the broker app has a token called PRT (primary refresh token) which it uses to fetch tokens for apps. This is how  "SSO" is achieved. 

MSAL falls back to a browser if the broker is not installed. Are you sure you are getting this error from the broker and not from the browser?

**Comment by harmjonker** [comment]
We use MSAL.net with broker option on...and we verify that users have MS Authenticator installed.

**Comment by bgavrilMS** [comment]
Ok. 

Is there any way to capture the broker incident from when this happens?

**Comment by harmjonker** [comment]
You mean the code you get when logging is sent from MS Authenticator?

**Comment by bgavrilMS** [comment]
Yes.

**Comment by harmjonker** [comment]
Hello Bogdan, this is an incident-id from MS Authenticator Log upload: XYGXMQVQ
This morning around 9:00 local time I started various apps to test single signon behavior. The first app failed on the first token acquire call and came back with the account selection box, after choosing an account it succeeded.

**Comment by bgavrilMS** [comment]
Hi Harm, I took a look at the logs (I can send them to you if you like). I cannot find anything related to this exception in the logs, even though there are entries for 9 AM.

I think we have 2 options to proceed here: 
- give us the [MSAL library logs ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging) to rule out any issues there, although I don't expect much since this is a server error. But we can make sure the broker is indeed used throughout.
- we can transfer the issue to https://github.com/AzureAD/microsoft-authentication-library-for-android as they own the auth logic on Authenticator. MSAL.NET only calls Authenticator and parses the result.

**Comment by harmjonker** [comment]
hello Bogdan,  we got a report from and end-user who could not login into one of the apps where it should be possible.
Authenticator logs sent with Incident-id: 26QPYWH, incident time was 17:20 h NL time, on nov. 15th. app name is Service Coach app. Could you have a look and see what happens around that time?

**Comment by bgavrilMS** [comment]
I was able to see a bunch of exception in the broker logs similar to: 

11-15 16:19:03:372 UTC ERROR/App: Error getting AAD accounts list Broker.getAllAccounts()@45 [AsyncTask #1]
11-15 16:19:03:374 UTC ERROR/App: java.lang.IllegalArgumentException: rawBytes
	at com.microsoft.identity.common.adal.internal.cache.StorageHelper.getSecretKey(StorageHelper.java:766)
	at com.microsoft.identity.common.adal.internal.cache.StorageHelper.loadSecretKey(StorageHelper.java:593)
	at com.microsoft.identity.common.adal.internal.cache.StorageHelper.decrypt(StorageHelper.java:316)
	at com.microsoft.identity.common.internal.cache.SharedPreferencesFileManager.encryptDecryptInternal(SharedPreferencesFileManager.java:265)
	at com.microsoft.identity.common.internal.cache.SharedPreferencesFileManager.decrypt(SharedPreferencesFileManager.java:252)
	at com.microsoft.identity.common.internal.cache.SharedPreferencesFileManager.getAll(SharedPreferencesFileManager.java:199)
	at com.microsoft.identity.common.internal.cache.SharedPreferencesAccountCredentialCache.getAccountsWithKeys(SharedPreferencesAccountCredentialCache.java:194)
	at com.microsoft.identity.common.internal.cache.SharedPreferencesAccountCredentialCache.getAccounts(SharedPreferencesAccountCredentialCache.java:225)
	at com.microsoft.identity.common.internal.cache.BrokerOAuth2TokenCache.getAccounts(BrokerOAuth2TokenCache.java:1083)
	at com.microsoft.identity.client.BrokerClientApplication.getAccounts(BrokerClientApplication.java:389)
	at com.azure.workaccount.Broker.getAllAccounts(Broker.java:37)
	at com.azure.authenticator.ui.fragment.accounts.MergeBrokerAccountsTask.doInBackground(MergeBrokerAccountsTask.java:67)
	at com.azure.authenticator.ui.fragment.accounts.MergeBrokerAccountsTask.doInBackground(MergeBrokerAccountsTask.java:24)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
 [AsyncTask #1]
