### ISSUE TITLE
[Bug][M] Interactive + System Browser fails if listening to localhost is forbidden - better error required

### ISSUE THREAD

**Issue by Steve0212a** [AzureAD/microsoft-authentication-library-for-dotnet#2219]
**Which Version of MSAL are you using ?**
Microsoft.Identity.Client 4.22.0

**Platform**
netcore

**What authentication flow has the issue?**
* Desktop / Mobile
    * [x] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [ ] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
Existing app that works on most machines, but fails on others

**Repro**
No special code to reproduce as this appears to be a Windows configuration issue.  When I called AcquireTokenInteractive(), everything worked on my development machine.  However, I had an end user that it would not work for.  He could authenticate using the software on my machine without issue, so I knew it was specific to his machine.  He did have VS 2019 on his machine, so I began debugging and it would throw the exception below when AcquireTokenInteractive() was called.

	System.Net.HttpListenerException (1214): The format of the specified network name is invalid.
	   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
	   at System.Net.HttpListener.AddAllPrefixes()
	   at System.Net.HttpListener.Start()
	   at Microsoft.Identity.Client.Platforms.Shared.DefaultOSBrowser.HttpListenerInterceptor.ListenToSingleRequestAndRespondAsync(Int32 port, Func`2 responseProducer, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.InterceptAuthorizationUriAsync(Uri authorizationUri, Uri redirectUri, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.AcquireAuthorizationAsync(Uri authorizationUri, Uri redirectUri, RequestContext requestContext, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)

I ended up bringing in the source code for Microsoft.Identity.Client and discovered that I got the exception on this line "httpListener.Start();" of HttpListenerInterceptor.cs.  I examined the url and it was valid at http://localhost:56874.  I then came across this article on stackoverflow for that error message with an HttpListener.
	https://stackoverflow.com/questions/47969786/c-sharp-httplistener-the-format-of-the-specified-network-name-is-not-valid

Sure enough, when I ran "netsh http show iplisten", 127.0.0.1 was not in the list.  I then ran "netsh http add iplisten 127.0.0.1" and authentication immediately began working on this machine.

**Expected behavior**
Authentication via AcquireTokenInteractive() should work on all machines or give a better error messages.

**Actual behavior**
if netsh iplisten is not properly set up to listen on 127.0.0.1, the call to AcquireTokenInteractive() throws an HttpListenerException().

**Possible Solution**
At the very least, please provide a better error message as this took me hours to figure out.  I am not sure why some machines have this netsh enabled and others don't.  It might be helpful to have a method that checks if this is properly configured since AcquireTokenInteractive() depends on it.  

**Additional context/ Logs / Screenshots**
	11:13:19.755   MSAL_LOGGING Error      True         (True) MSAL 4.22.0.0 MSAL.NetCore Microsoft Windows 10.0.19042 [11/19/2020 16:13:19 - 847293f7-d6b6-434e-8830-fb5c67e105ad] System.Net.HttpListenerException (1214): The format of the specified network name is invalid.
	   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
	   at System.Net.HttpListener.AddAllPrefixes()
	   at System.Net.HttpListener.Start()
	   at Microsoft.Identity.Client.Platforms.Shared.DefaultOSBrowser.HttpListenerInterceptor.ListenToSingleRequestAndRespondAsync(Int32 port, Func`2 responseProducer, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.InterceptAuthorizationUriAsync(Uri authorizationUri, Uri redirectUri, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Platforms.Shared.Desktop.OsBrowser.DefaultOsBrowserWebUi.AcquireAuthorizationAsync(Uri authorizationUri, Uri redirectUri, RequestContext requestContext, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
	   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)

**Comment by bgavrilMS** [comment]
Thanks for investigating the root cause @Steve0212a, we prioritize #supportability bugs high.

**Comment by Steve0212a** [comment]
Glad to hear it.  Thanks for the update!

**Comment by bgavrilMS** [comment]
@Steve0212a - do you know what could cause this ? Does the end-user have Win Server or maybe an admin policy that prevents listening on localhost:port ?

**Comment by Steve0212a** [comment]
I honestly have no idea.  It is a corporate Win 10 Pro system.

However, I was just installing a Win 10 Pro system in a VM..  It was not joined to a domain as it was a brand new install.  I ran "netsh http show iplisten".  The list was empty on the brand new machine.

**Comment by bgavrilMS** [comment]
On my machine that list is also empty and the auth flow / http listener works fine

**Comment by Steve0212a** [comment]
strange - that change fixed the auth flow immediately as soon as I ran the "add iplisten" command.  definitely was something preventing the listener from listening.  Not sure how yours can work without that setting.

**Comment by bgavrilMS** [comment]
I can think of a few things that could go wrong in this whole setup. As per https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost, it's clear that either a bad DNS entry or a custom configuration where localhost is not mapped to 127.0.0.1 could cause a problem. Aso see https://github.com/github/VisualStudio/issues/2554

We could try an actual fix here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/41ee0a686ebebfb20649f3beebc09ae79d08c2ae/src/client/Microsoft.Identity.Client/Platforms/Features/DefaultOSBrowser/HttpListenerInterceptor.cs#L39 - instead of listening to "http://localhost:port" we could listen to "http:/127.0.0.1:port". Note that we cannot change the redirect URI, from AAD's point of view "localhost"!="127.0.0.1" (string comparison)

I am a bit hesitant to introduce this sort of change though as it would require testing for what seems to be 1 user with a strange config. I think adding a better error message with some troubleshooting steps would be a better approach.

**Comment by Steve0212a** [comment]
I think the error message approach is good - and also perhaps add a way to override the default value of localhost on the line below.  That would give end users the ability to change it to 127.0.0.1 if needed...

`string urlToListenTo = "http://localhost:" + port + "/"; `

**Comment by RhomGit** [comment]
I have a solitary production user on Win 10 Pro experiencing an issue with interactive (no UI is presented when Sign In is clicked).

> strange - that change fixed the auth flow immediately as soon as I ran the "add iplisten" command

Did you run something to resolve this issue? I have only just begun investigating my issue and wonder if its the same. Difficult for me since its a remote client in a different timezone so any info would be great. I don't have the luxury of them running source code in Visual Studio haha.

**Comment by bgavrilMS** [comment]
@RhomGit I think the solution proposed by @Steve0212a was to run `netsh http add iplisten 127.0.0.1` from an Admin cmd line.

**Comment by pmaytak** [comment]
This is included in [MSAL 4.30.0 release](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.30.0).
