### ISSUE TITLE
A certificate with a private secret is required

### ISSUE THREAD

**Issue by toburger** [AzureAD/microsoft-authentication-library-for-dotnet#2435]
I couldn't find any requirement for a certificate with a private secret in the [documentation](
https://docs.microsoft.com/en-us/azure/active-directory/authentication/active-directory-certificate-based-authentication-get-started).

However the lib is throwing an error if trying to use a certificate without a private secret:
```
MSAL.Desktop.4.27.0.0.MsalClientException: 
	ErrorCode: cert_without_private_key
Microsoft.Identity.Client.MsalClientException: The certificate certificate does not have a private key. 
   at Microsoft.Identity.Client.ConfidentialClientApplicationBuilder.WithCertificate(X509Certificate2 certificate)
```

This happens when I try to build the app via `ConfidentialClientApplicationBuilder` with version 4.0.

Version 3.0 let's me build the app, but when I try to acquire a token I get the error:
```
System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: The private key is not present in the X.509 certificate.
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetAsymmetricAlgorithm(String algorithm, Boolean privateKey)
   at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientAssertionCertificateWrapper credential, Boolean sendCertificate)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialHelper.CreateClientCredentialBodyParameters(ICoreLogger logger, ICryptographyManager cryptographyManager, ClientCredentialWrapper clientCredential, String clientId, AuthorityEndpoints endpoints, Boolean sendX5C)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
...
```

**Comment by toburger** [comment]
Turns out the wrong certificate was handled out to me.
