### ISSUE TITLE
[Bug][L] ConfidentialClient does not support ECDsa client application certificates.

### ISSUE THREAD

**Issue by fuocor** [AzureAD/microsoft-authentication-library-for-dotnet#2573]
**Which Version of MSAL are you using ?**
4.30

**Platform**
APSNETCORE 5.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App 
    * [x] Authorization code
    * [ ] OBO
* Daemon App 
    * [ ] Service to Service calls

Other? - please describe;

**Is this a new or existing app?**
existing
**Repro**
1. Register an AzureAD confidential client application with a certificate using ECDsa
2. Create an instance on the ConfidentialClient
3. Try and acquire an OBO token

```csharp
var onBehalfOfClientApplication = await this.oauthTokenProvider.BindAsync(accountId, this.TenantId).ConfigureAwait(false);

var oboResult = await onBehalfOfClientApplication
    .AcquireTokenOnBehalfOf(oauthScopes, userAssertion)
    .ExecuteAsync().ConfigureAwait(false);
```

**Expected behavior**
A token.

**Actual behavior**
```
      System.NotSupportedException: The certificate key algorithm is not supported.
         at System.Security.Cryptography.X509Certificates.PublicKey.get_Key()
         at Microsoft.Identity.Client.Platforms.netcore.NetCoreCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)
         at Microsoft.Identity.Client.Internal.ClientCredentialWrapper.Sign(ICryptographyManager cryptographyManager, String message)
         at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendCertificate)
         at Microsoft.Identity.Client.Internal.Requests.ClientCredentialHelper.CreateClientCredentialBodyParameters(ICoreLogger logger, ICryptographyManager cryptographyManager, ClientCredentialWrapper clientCredential, String clientId, AuthorityEndpoints endpoints, Boolean sendX5C)
         at Microsoft.Identity.Client.OAuth2.TokenClient.AddBodyParamsAndHeaders(IDictionary`2 additionalBodyParameters, String scopes)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.OnBehalfOfRequest.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenOnBehalfOfParameters onBehalfOfParameters, CancellationToken cancellationToken)
         at Chorus.Services.Application.ChorusServerApplication.AssignTenantOwnerAsync(TenantOptions tenantOptions, AuthenticationResult authenticationResult, TrackedTelemetry trackedTelemetry, CancellationToken cancellationToken) in C:\Ossiaco\chorus\src\Chorus.Services\src\Application\ChorusServerApplication.cs:line 94
         at Chorus.Services.Configure.Azure.ChorusResourceManager.<>c__DisplayClass12_1.<<ConfigureChorusApplicationAsync>b__2>d.MoveNext() in C:\Ossiaco\chorus\src\Chorus.Services.Configure\src\Azure\ChorusResourceManager.cs:line 374
```

**Comment by jmprieur** [comment]
Is it at all supported by .NET 5.0 ?

**Comment by fuocor** [comment]
Yes. the crypto libraries have all the code in place

**Comment by fuocor** [comment]
you cannot use `System.Security.Cryptography.X509Certificates.PublicKey` or `System.Security.Cryptography.X509Certificates.PrivateKey`, you need to use the `Get` methods.

**Comment by bgavrilMS** [comment]
How did you create an ECDsa cert @fuocor ?

**Comment by bgavrilMS** [comment]
Here's the code we use to sign, obviously it's very RSA oriented ... 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/0d53f3e80e29f9c6d172e069c10e02d71e24f65e/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CryptographyManager.cs#L16

**Comment by fuocor** [comment]
to create the cert. Just change up the `X509KeyUsageFlags`  and `BasicConstraints`. I zipped up the relevant files minus the CertificateRequest decoder.

```csharp
        public static (CertificateRequest CertificateRequest, ECDsa PrivateKey) NewECDsaCertificateRequest(this DistinguishedName distinguishedName, ECDsaConfiguration? eCDsaConfiguration = null)
        {
            eCDsaConfiguration ??= new();
            var ecdsa = Guard.Verify.IsNotNull(ECDsa.Create(ECCurve.NamedCurves.nistP521), nameof(ECDsa));
            ecdsa.KeySize = eCDsaConfiguration.KeySize;
            var certificateRequest = new CertificateRequest(CreateIssuerOrSubject(distinguishedName), ecdsa, eCDsaConfiguration.HashAlgorithmName);
            return (certificateRequest, ecdsa);
        }
```
``` csharp
        public static X509Certificate2 NewECDsaRootCertificate(this DistinguishedName distinguishedName, ValidityPeriod validityPeriod, int pathLengthConstraint, SubjectAlternativeName subjectAlternativeName)
        {
            var enhancedKeyUsages = new OidCollection
[ECDas.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6359721/ECDas.zip)

            {
                OidLookup.ClientAuthentication,
                OidLookup.ServerAuthentication,
            };

            var basicConstraints = new BasicConstraints
            {
                CertificateAuthority = true,
                HasPathLengthConstraint = true,
                PathLengthConstraint = pathLengthConstraint,
                Critical = true,
            };

            var x509KeyUsageFlags = X509KeyUsageFlags.KeyCertSign;
            var (certificateRequest, _) = NewECDsaCertificateRequest(distinguishedName);
            certificateRequest.AddBasicConstraints(basicConstraints);
            certificateRequest.AddExtendedKeyUsages(x509KeyUsageFlags);
            certificateRequest.AddSubjectAlternativeName(subjectAlternativeName);
            certificateRequest.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension(enhancedKeyUsages, false));
            certificateRequest.CertificateExtensions.Add(new X509SubjectKeyIdentifierExtension(certificateRequest.PublicKey, false));
            var notbefore = validityPeriod.ValidFrom.AddDays(-1);
            var notafter = validityPeriod.ValidTo;
            return certificateRequest.CreateSelfSigned(notbefore, notafter);
        }
```

**Comment by fuocor** [comment]
I'm not sure the zip made it into the last message. 
[ECDas.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6359736/ECDas.zip)

**Comment by jmprieur** [comment]
Also, is ECDsa supported service side?

**Comment by fuocor** [comment]
yep

**Comment by fuocor** [comment]
change your implementation to this in order to make it work. It wall also verify the validity of the signing certificate:
```csharp
   internal static class CryptographyManager
    {
        private static readonly ConcurrentDictionary<string, AsymmetricAlgorithm> CertificateToAsymmetricAlgorithmMap = new ConcurrentDictionary<string, AsymmetricAlgorithm>();
        private static readonly int MaximumMapSize = 1000;

        public static byte[] SignWithCertificate(string message, X509Certificate2 certificate)
        {
            using var chain = new X509Chain
            {
                ChainPolicy = BuildChainPolicyChained(),
            };

            var certificateIsValid = chain.Build(certificate);
            if (!certificateIsValid)
            {
                var chainErrors = new List<X509ChainStatusFlags>();
                foreach (var validationFailure in chain.ChainStatus)
                {
                    chainErrors.Add(validationFailure.Status);
                }

                throw new InvalidCastException($"An invalid certificate was supplied. {string.Join(", ", chainErrors.Select(e => e.ToString()))}");
            }

            if (!CertificateToAsymmetricAlgorithmMap.TryGetValue(certificate.Thumbprint, out var alg))
            {
                if (CertificateToAsymmetricAlgorithmMap.Count >= MaximumMapSize)
                {
                    CertificateToAsymmetricAlgorithmMap.Clear();
                }

#if NET5_0_OR_GREATER
                alg = certificate.GetRSAPrivateKey() ?? certificate.GetECDsaPrivateKey() ?? (AsymmetricAlgorithm?)certificate.GetDSAPrivateKey() ?? throw new NotSupportedException("The certificate key algorithm is not supported.");
#else
                alg = certificate.GetRSAPrivateKey() ?? (AsymmetricAlgorithm?)certificate.GetECDsaPrivateKey() ?? throw new NotSupportedException("The certificate key algorithm is not supported.");
#endif
            }

            var signedData = alg switch
            {
                RSA rsa => rsa.SignData(Encoding.UTF8.GetBytes(message), HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1),
                ECDsa eCDsa => eCDsa.SignData(Encoding.UTF8.GetBytes(message), HashAlgorithmName.SHA256),
#if NET5_0_OR_GREATER
                DSA dsa => dsa.SignData(Encoding.UTF8.GetBytes(message), HashAlgorithmName.SHA256),
#endif
                _ => throw new NotSupportedException("The certificate key algorithm is not supported."),
            };

            // Cache only valid crypto providers, which are able to sign data successfully
            CertificateToAsymmetricAlgorithmMap[certificate.Thumbprint] = alg;
            return signedData;
        }

        private static X509ChainPolicy BuildChainPolicyChained(
            X509VerificationFlags verificationFlags = X509VerificationFlags.AllowUnknownCertificateAuthority,
            X509RevocationFlag revocationFlag = X509RevocationFlag.EndCertificateOnly,
            X509RevocationMode revocationMode = X509RevocationMode.NoCheck)
        {
            var chainPolicy = new X509ChainPolicy
            {
                VerificationFlags = verificationFlags,
                RevocationFlag = revocationFlag,
                RevocationMode = revocationMode,
            };

            _ = chainPolicy.ApplicationPolicy.Add(OidLookup.DocumentSigning);
            return chainPolicy;
        }
    }
```

**Comment by bgavrilMS** [comment]
Thanks for this @fuocor - it's a great start. We need to do more to get this into the product, especially around having E2E tests with the different types of cert. 

For now, I suggest you use an MSAL extensibility mechanism that allows app developers (you) to perform the signing operation instead of MSAL. This is described here: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Assertions#signed-assertions

**Comment by bgavrilMS** [comment]
@henrik-me  @jmprieur - since ESTS most likely supports these certs, it should be a nice improvement to our CCA scenarios? MSAL 4.32?

**Comment by jmprieur** [comment]
@bgavrilMS @henrik-me 
yes, I agree. let's prioritize it.

**Comment by neha-bhargava** [comment]
@fuocor were you able to get a token from ests using the workaround provided above?

**Comment by fuocor** [comment]
I haven't actually had the time to look into using Signed Assertions. For the moment I reverted the application certificate back to self-signed RSA. If this gets implemented in the upcoming weeks, then I will go back to using my PKI ECDsa certificates.

**Comment by neha-bhargava** [comment]
@fuocor We just came to know from ests that ECDsa certs are not supported by them. They only support RSA certs. Closing this issue as we will not be able to support ECDsa certs.
