### ISSUE TITLE
Exception "Method not found: 'Void Microsoft.Web.WebView2.WinForms.WebView2.add_AcceleratorKeyPressed" when calling AcquireTokenInteractive

### ISSUE THREAD

**Issue by twieczor** [AzureAD/microsoft-authentication-library-for-dotnet#2685]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**
MSAL.NET 4.32.0

**Platform**
.NET 4.6

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
Microsoft Edge WebView2 Runtime ver. 91.0.864.41

**Is this a new or existing app?**
c. This is a new app or experiment.

**Repro**

```csharp
IMsalHttpClientFactory factoryHttpClient = new MsalClientFactory("user agent");
IPublicClientApplication client = PublicClientApplicationBuilder
                         .Create("client Id")
                         .WithDesktopFeatures()
                         .WithHttpClientFactory(factoryHttpClient)
                         .WithAuthority("authority")
                         .Build();

var authResult = await client.AcquireTokenInteractive(scopes).WithUseEmbeddedWebView(true)
                        .WithLoginHint("loginHint").WithPrompt(Prompt.NoPrompt)
                       .ExecuteAsync(cancelToken).ConfigureAwait(true);
```

**Expected behavior**
authResult returns access token

**Actual behavior**
Exception:
Method not found: 'Void Microsoft.Web.WebView2.WinForms.WebView2.add_AcceleratorKeyPressed(System.EventHandler`1<Microsoft.Web.WebView2.Core.CoreWebView2AcceleratorKeyPressedEventArgs>)'.

**Possible solution**

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots. 

<GetEwsToken>d__16.MoveNext, Line 270] : Error acquiring access token
System.MissingMethodException: Method not found: 'Void Microsoft.Web.WebView2.WinForms.WebView2.add_AcceleratorKeyPressed(System.EventHandler`1<Microsoft.Web.WebView2.Core.CoreWebView2AcceleratorKeyPressedEventArgs>)'.
   at Microsoft.Identity.Client.Platforms.Features.WebView2WebUi.WebView2WebUi.<AcquireAuthorizationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceVerifierAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()

System.MissingMethodException: Method not found: 'Void Microsoft.Web.WebView2.WinForms.WebView2.add_AcceleratorKeyPressed(System.EventHandler`1<Microsoft.Web.WebView2.Core.CoreWebView2AcceleratorKeyPressedEventArgs>)'.
   at Microsoft.Identity.Client.Platforms.Features.WebView2WebUi.WebView2WebUi.<AcquireAuthorizationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceVerifierAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()

**Comment by pmaytak** [comment]
@bgavrilMS I vaguely remember getting something like this when I upgraded WebView2 SDK in MSAL (while testing something else). In this case, feels like it might be a back compat issue with the WebView2 runtime? (Because I think it worked for me on runtime 91.x). Might also want to consider updating to the latest SDK ([1.0.864.35](https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes#1086435)) or do we need to stay on the lower version?

**Comment by twieczor** [comment]
I believe WebView2.AcceleratorKeyPressed event has been depraciated since 1.0.774.44, that was 3 releases ago.

**Comment by bgavrilMS** [comment]
I don't understand how this can happen, we took a dependency on a stable (non pre-release) version of the SDK    
`<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.705.50" />`

**Comment by pmaytak** [comment]
@twieczor You are right it was removed since 1.0.774.44. 
I created a test app (net461/netcoreapp3.1) that uses just MSAL. WebView2 works correctly since 1.0.705.50 version is pulled from MSAL. 
If I add a direct reference to a newer WebView2 NuGet in my app, the newer WebView2 reference is picked up and the error does happen. Do you directly import a newer version of WebView2 SDK in your app? The workaround would be to either remove any direct reference to newer WebView2 NuGet (and transitively get it from MSAL) or downgrade it to 1.0.705.50.

**Comment by pmaytak** [comment]
For reference: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1453

**Comment by pmaytak** [comment]
@bgavrilMS Based on the https://github.com/MicrosoftEdge/WebView2Feedback/issues/1453#issuecomment-871711806, if we upgrade WebView2 SDK version, we'll have to use `OnKeyDown` instead of `AcceleratorKeyPressed`. 

Another point is that these events block all shortcut keys like CTRL + V, arrow keys. I think we might need to update the event handler to allow copy, paste, and such. Another alternative is to maybe set `WebView2.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled` which doesn't disable all the keys.

**Comment by twieczor** [comment]
@pmaytak Unfortunately, we use WebView2 SDK directly, and can't downgrade it. Hopefully the new MSAL will solve this.
