### ISSUE TITLE
[Bug] When using AcquireTokenByIntegratedWindowsAuth against ADFS, we should send a better error message when encountering 401

### ISSUE THREAD

**Issue by maliksahil** [AzureAD/microsoft-authentication-library-for-dotnet#2752]
**Logs and network traces**
Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

**Which version of MSAL.NET are you using?**

4.33

**Platform**

Windows, all versions of .NET

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**

**Repro**

```csharp
 string[] scopes = new string[] { "user.read" };
 IPublicClientApplication app = PublicClientApplicationBuilder
      .Create(clientId)
      .WithAuthority(authority)
      .Build();
result = await app.AcquireTokenByIntegratedWindowsAuth(scopes).ExecuteAsync(CancellationToken.None);
```

**Expected behavior**

Usually this call should succeed, but when this endpoint `https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport` sends back a 401, we send a very cryptic exception back, we should send an UnAuthorizedException or something appropriate.

**Actual behavior**

The exception we send back is this, 
```
Error code: parsing_wstrust_response_failed. Error message: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport returned error:
    ---> Microsoft.Identity.Client.MsalServiceException: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport returned error:  \r\n
    at Microsoft.Identity.Client.WsTrust.WsTrustWebRequestManager.<GetWsTrustResponseAsync>d__3.MoveNext()
```

**Possible solution**

We should look for 401 return code in the message before parsing the result blindly. For a 401, we should send back an UnAuthorizedException. In fact we should look for common HTTP error codes, and bubble to appropriate exception back to the client, so they can diagnose this easier.

**Additional context / logs / screenshots**
Add any other context about the problem here, such as logs and screenshots. 

Full exception trace from customer,
```
Error : PAD.MachineRegistration.Silent.SilentRegistrationException: Failed to acquire token silently. You can retry with a fallback mechanism. See -help above. Error code: parsing_wstrust_response_failed. Error message: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport returned error: ---> Microsoft.Identity.Client.MsalClientException: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport returned error: ---> Microsoft.Identity.Client.MsalServiceException: Federated service at https://msft.sts.microsoft.com/adfs/services/trust/13/windowstransport returned error: at Microsoft.Identity.Client.WsTrust.WsTrustWebRequestManager.<GetWsTrustResponseAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.<GetWsTrustResponseAsync>d__6.MoveNext() --- End of inner exception stack trace --- at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.<GetWsTrustResponseAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.<PerformWsTrustMexExchangeAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<FetchAssertionFromWsTrustAsync>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<ExecuteAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__13.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at WinAutomation.MsAccountAuthenticator.MicrosoftAuthenticationService.<>c__DisplayClass15_0.<<GetAccessTokenByIntegratedWindowsAuthAsync>g__GetAccessTokenFromIntegratedWindowsInternalAsync|0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at WinAutomation.MsAccountAuthenticator.MicrosoftAuthenticationService.<GetAccessTokenWithXYZAsync>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at WinAutomation.MsAccountAuthenticator.MicrosoftAuthenticationService.<GetAccessTokenByIntegratedWindowsAuthAsync>d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at PAD.MachineRegistration.Silent.Operations.SilentRegistrationOperations.<>c__DisplayClass14_0.<<TryLogonAsync>g__TryLogonInternalAsync|0>d.MoveNext() --- End of inner exception stack trace --- at PAD.MachineRegistration.Silent.Operations.SilentRegistrationOperations.<>c__DisplayClass14_0.<<TryLogonAsync>g__TryLogonInternalAsync|0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at WinAutomation.Logging.LoggerTraceOperationExtensions.<TraceOperationAsync>d__12`1.MoveNext()
```

**Comment by bgavrilMS** [comment]
Not sure about UnAuthroizedException. MSAL throws MsalClientException or MsalServiceException exceptions to denote library problems and server problems respectively. 

I think MsalServiceException is better here. 

But totally agree that we need to improve this experience by throwing a good exception.

**Comment by bgavrilMS** [comment]
CC @trwalke for general IWA

**Comment by trwalke** [comment]
While debugging the code I did not get back the 401. It was 200 actually. I added a better message to the parsing error that is encountered.
