### ISSUE TITLE
"Non-HTTPS url redirect is not supported in webview" MsalServiceException

### ISSUE THREAD

**Issue by JaykeBird** [AzureAD/microsoft-authentication-library-for-dotnet#286]
Greetings! I'm using the Microsoft.Identity.Client library in a some beta software right now, and I encountered this exception while trying to log in to a personal Microsoft account.

More info:

I logged into my personal Microsoft account through the sign-in dialog provided by the library (without issue), and my program crashed soon afterwards due to an unrelated reason. When I restarted my application (after resolving that crash) and went to log in again, my personal Microsoft account was already listed as an option in the sign-in dialog.

I selected it, there was a moment of loading, and then the "allow this app to access your info?" screen appeared for a moment before the dialog suddenly closed and I got this MsalServiceException.

Clicking "Sign out" or "Sign out and forget" didn't seem to work, as well.

Stack trace:

`   at Microsoft.Identity.Client.Handlers.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.Identity.Client.Handlers.AcquireTokenInteractiveHandler.<PreTokenRequest>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Handlers.AcquireTokenHandlerBase.<RunAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenCommonAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()
   at ShineWin.Connect.Msal.Auth.<ConnectNewAccount>d__2.MoveNext() in C:\Users\Jacob\Documents\Visual Studio 2015\Projects\ShineCalendar\ShineConnect\Msal\Auth.cs:line 39`

**Comment by kpanwar** [comment]
Did you click on "More Details" link on the consent page? If so then it is related to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/284

**Comment by JaykeBird** [comment]
[This is what I see.](https://1drv.ms/i/s!AnYp1YFqE6kPgeps4kvRcdzpSXDfBg) My apologies, but I don't see a "More Details" link. Maybe that's a link that appears when using a work or school account?

On the first go-around (the time when my app crashed after logging in), I had clicked on my app's "Terms" link at the bottom of the page and the "application permissions" link.

On the second time around (when this exception started appearing), the exception would appear nearly instantly after this screen appeared, before I could even click anything.

Right now, it's working again, so whatever was going on isn't happening anymore here.
