### ISSUE TITLE
"WS-Trust endpoint not found in metadata document." when using Windows authentication with ADFS 

### ISSUE THREAD

**Issue by digiofficerobin** [AzureAD/microsoft-authentication-library-for-dotnet#3122]
**Logs and network traces**
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:27.88 - b408c935-46b7-4603-af87-912f32ecbec6] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:27.93] [WAM Broker] Using desktop as a parent window.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:27.94] WAM::FindAllAccountsAsync returning no accounts due to configuration option
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:27.95 - f401238c-afe6-414a-9d01-b100778c9641] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:27.95] Found 0 cache accounts and 0 broker accounts
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:27.95] Returning 0 accounts
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:32.71 - bd3705c4-2196-4183-9d31-5987774311cc] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:32.71] [WAM Broker] Using desktop as a parent window.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:32.71] WAM::FindAllAccountsAsync returning no accounts due to configuration option
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:32.71 - 226aeba1-1971-4bc2-853a-c5d6e0581457] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:32.71] Found 0 cache accounts and 0 broker accounts
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:32.71] Returning 0 accounts
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.74 - 9a61eaa5-830d-4e2e-ab39-88a7096689e3] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.74] [WAM Broker] Using desktop as a parent window.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.74] WAM::FindAllAccountsAsync returning no accounts due to configuration option
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.74 - ffce5215-bb15-4cae-9e36-b71e140f8f3c] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.74] Found 0 cache accounts and 0 broker accounts
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.74] Returning 0 accounts
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.75 - 51f84be0-ee39-4f8a-b37c-07b20c769425] MSAL MSAL.Desktop with assembly version '4.36.0.0'. CorrelationId(51f84be0-ee39-4f8a-b37c-07b20c769425)
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.75 - 51f84be0-ee39-4f8a-b37c-07b20c769425] 
=== Request Data ===
Authority Provided? - True
Scopes - user.read
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenByIntegratedWindowsAuth
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - True
HomeAccountId - False
CorrelationId - 51f84be0-ee39-4f8a-b37c-07b20c769425

Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.76 - 51f84be0-ee39-4f8a-b37c-07b20c769425] === Token Acquisition (IntegratedWindowsAuthRequest) started:
	 Scopes: user.read
	Authority Host: login.microsoftonline.com
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.76 - 51f84be0-ee39-4f8a-b37c-07b20c769425] [Region discovery] Azure region was not configured or could not be discovered. Not using a regional authority.
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:33.77 - 51f84be0-ee39-4f8a-b37c-07b20c769425] Fetching instance discovery from the network from host login.microsoftonline.com. 
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:38.16 - 51f84be0-ee39-4f8a-b37c-07b20c769425] Authority validation enabled? True. 
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:38.16 - 51f84be0-ee39-4f8a-b37c-07b20c769425] Authority validation - is known env? True. 
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:38.17 - 51f84be0-ee39-4f8a-b37c-07b20c769425] Logged in user detected. 
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:38.17 - 51f84be0-ee39-4f8a-b37c-07b20c769425] Sending request to userrealm endpoint. 
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:41.09 - 51f84be0-ee39-4f8a-b37c-07b20c769425] 
Info;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:41.83 - 51f84be0-ee39-4f8a-b37c-07b20c769425] Fetched and parsed MEX
Error;False MSAL 4.36.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [01/24 18:48:41.85 - 51f84be0-ee39-4f8a-b37c-07b20c769425] Exception type: Microsoft.Identity.Client.MsalClientException
, ErrorCode: wstrust_endpoint_not_found

   at Microsoft.Identity.Client.WsTrust.CommonNonInteractiveHandler.<PerformWsTrustMexExchangeAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<FetchAssertionFromWsTrustAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.IntegratedWindowsAuthRequest.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()

**Which version of MSAL.NET are you using?**
MSAL.NET 4.36.0

**Platform**
.NET 4.6.1 winform

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
The app is in production.

To reproduce the problem in a simple setting it is reproducible with a simple toy application (see attachment).

**Repro**
1. Download project source (see attachment)
2. Register an Client app (https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app)
3. Put the ClientID in file App.xml.cs
4. Build and Run the application
5. Choose Windows authentication
6. Click on button 'Call Microsoft Graph API'

scenario 1: logged in with Windows authentication and connected to the LAN
The app can successfully acquire a ID and Access token in with Integrated Windows authentication

![image](https://user-images.githubusercontent.com/16424069/150844443-4b722826-bdf7-4c6f-a26c-45d9850ca397.png)

scenario 2: logged in with Windows authentication on your laptop and connected to the internet (no VPN, etc.)
The app cannot successfully acquire an ID and Access token. 

![image](https://user-images.githubusercontent.com/16424069/150845676-6fedc386-26f3-4122-80ea-a318f726edf6.png)

(see log above this Issue)

```csharp
authResult = await app.AcquireTokenByIntegratedWindowsAuth(scopes).ExecuteAsync();
```

**Expected behavior**
I would expect an Access token, even when I'm in the field on a open internet Wifi connection (i.e. at home) and not directly plugged in the corporate LAN. While requesting a token for the Graph API I would except that I do not have to give my username/password or other credentials, because I am already logged in the domain connected PC. The account is synchronized from the local AD to Azure AD. And an ADFS server handles the authentications who come from the internet.

**Actual behavior**
An exception of "Exception type: Microsoft.Identity.Client.MsalClientException, ErrorCode: wstrust_endpoint_not_found" is given.

**Possible solution**
We are unsure if it is our configuration in ADFS and/or this is a problem in de MSAL.NET library. The trust/mex file can be found here: 
![image](https://user-images.githubusercontent.com/16424069/150847166-42da7adc-a7cf-4c07-806f-643b5b267d86.png)

We have tested this scenario with an Azure AD connected Windows client pc. This was successful.

**Additional context / logs / screenshots / links to code**
[active-directory-wpf-msgraph-v2.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/7928160/active-directory-wpf-msgraph-v2.zip)

**Comment by bgavrilMS** [comment]
This is most likely a configuration issue, please see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Integrated-Windows-Authentication#troubleshooting and https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa
