### ISSUE TITLE
Blank popup and System.NullReferenceException from WebView2

### ISSUE THREAD

**Issue by bvirkler** [AzureAD/microsoft-authentication-library-for-dotnet#3161]
**Which version of MSAL.NET are you using?**
MSAL.NET 4.41.0

**Platform**
.NET 6 Winforms

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
This is a new App

**Repro**

```csharp
            var publicClientOptions = new PublicClientApplicationOptions()
            {
                RedirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient",
                AadAuthorityAudience = AadAuthorityAudience.AzureAdMyOrg,
                AzureCloudInstance = AzureCloudInstance.AzurePublic,
                ClientId = clientId,
                TenantId = "xxxx"
            };

            var app = PublicClientApplicationBuilder
                .CreateWithApplicationOptions(publicClientOptions)
                .WithLogging(MyLoggingMethod, LogLevel.Verbose, false, true)
                .Build();

            AuthenticationResult authResult;
            try
            {
                var accounts = await app.GetAccountsAsync().ConfigureAwait(false);
                authResult = await app.AcquireTokenSilent(scopesForToken, accounts.FirstOrDefault())
                    .ExecuteAsync().ConfigureAwait(false);
            }
            catch (MsalUiRequiredException ex)
            {
                authResult = await app.AcquireTokenInteractive(scopesForToken)
                    .WithClaims(ex.Claims)
                    .WithUseEmbeddedWebView(true)
                    .ExecuteAsync().ConfigureAwait(false);
            }

            return authResult.AccessToken;
```

**Expected behavior**
When interactive auth is required, the embedded webview pops up, user completes auth process, and an auth result is returned.

**Actual behavior**
Embedded webview pops up and hangs with a blank window (see screenshot below).  Closing the popup results in a "user cancelled authentication" MsalClientException.

Running in debug mode in Visual Studio shows the following exception:
```
System.NullReferenceException
   at Microsoft.Identity.Client.Platforms.Features.WebView2WebUi.WinFormsPanelWithWebView2.WebView2Control_CoreWebView2InitializationCompleted(Object sender, CoreWebView2InitializationCompletedEventArgs e)
```

**Additional context / logs / screenshots / links to code**
Blank popup:
![image](https://user-images.githubusercontent.com/347725/154102595-ab5cc327-a228-4810-a45a-5aba66cdfad6.png)

MSAL Logging:
```
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] [Cache Session Manager] Entering the cache semaphore. Real semaphore: True. Count: 1
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] [Cache Session Manager] Entered cache semaphore
MSAL Always False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z] [Clear] Clearing access token cache data.
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] [Cache Session Manager] Released cache semaphore
MSAL Always False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z] [GetAllAccessTokens] Total number of cache partitions found while getting refresh tokens: 1
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] GetAccounts found 2 RTs and 1 accounts in MSAL cache. 
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] IsLegacyAdalCacheEnabled: yes
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] [Region discovery] Not using a regional authority. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] [Instance Discovery] Tried to use known metadata provider for login.microsoftonline.com. Success? True. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] GetAccounts found 2 RTs and 1 accounts in MSAL cache after environment filtering. 
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] IsLegacyAdalCacheEnabled: yes
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - f2dc297f-0089-4abc-bdfb-bcc580440584] IsLegacyAdalCacheEnabled: yes
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z] Found 0 cache accounts and 0 broker accounts
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z] Returning 0 accounts
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] MSAL MSAL.NetCore with assembly version '4.40.0.0'. CorrelationId(8c257af3-d56c-4121-894a-df390b5c9a18)
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] === AcquireTokenSilent Parameters ===
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] LoginHint provided: False
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] Account provided: False
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] ForceRefresh: False
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] 
=== Request Data ===
Authority Provided? - True
Scopes - api://0b33f671-5684-4ae8-b410-b364712d52e7/.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 8c257af3-d56c-4121-894a-df390b5c9a18
UserAssertion set: False
LongRunningOboCacheKey set: False

MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] === Token Acquisition (SilentRequest) started:
	 Scopes: api://0b33f671-5684-4ae8-b410-b364712d52e7/.default
	Authority Host: login.microsoftonline.com
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] No account passed to AcquireTokenSilent. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] Token cache could not satisfy silent request.
MSAL Error False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - 8c257af3-d56c-4121-894a-df390b5c9a18] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
, ErrorCode: user_null
HTTP StatusCode 0
CorrelationId 

   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] MSAL MSAL.NetCore with assembly version '4.40.0.0'. CorrelationId(a464c330-78ac-44ba-a7c2-49371b85d95a)
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] === InteractiveParameters Data ===
LoginHint provided: False
User provided: False
UseEmbeddedWebView: Embedded
ExtraScopesToConsent: 
Prompt: not_specified
HasCustomWebUi: False

MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] 
=== Request Data ===
Authority Provided? - True
Scopes - api://0b33f671-5684-4ae8-b410-b364712d52e7/.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenInteractive
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - a464c330-78ac-44ba-a7c2-49371b85d95a
UserAssertion set: False
LongRunningOboCacheKey set: False

MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] === Token Acquisition (InteractiveRequest) started:
	 Scopes: api://0b33f671-5684-4ae8-b410-b364712d52e7/.default
	Authority Host: login.microsoftonline.com
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] [Region discovery] Not using a regional authority. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False. 
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Fetching instance discovery from the network from host login.microsoftonline.com. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Starting [Oauth2Client] Sending GET request 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Starting [HttpManager] ExecuteAsync
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:13Z - a464c330-78ac-44ba-a7c2-49371b85d95a] [HttpManager] Sending request. Method: GET. Host: https://login.microsoftonline.com. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] [HttpManager] Received response. Status code: OK. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Finished [HttpManager] ExecuteAsync in 267 ms
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Finished [Oauth2Client] Sending GET request  in 274 ms
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Starting [OAuth2Client] Deserializing response
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Finished [OAuth2Client] Deserializing response in 57 ms
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? True. 
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] [Instance Discovery] After hitting the discovery endpoint, the network provider found an entry for login.microsoftonline.com ? True. 
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Authority validation enabled? False. 
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Authority validation - is known env? True. 
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Using WebView2 embedded browser.
MSAL Verbose False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:14Z - a464c330-78ac-44ba-a7c2-49371b85d95a] [WebView2Control] CoreWebView2InitializationCompleted 
MSAL Info False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:18Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Authorization result status returned user cancelled authentication. 
MSAL Error False False MSAL 4.40.0.0 MSAL.NetCore .NET 6.0.2 Microsoft Windows 10.0.19043 [2022-02-15 15:37:18Z - a464c330-78ac-44ba-a7c2-49371b85d95a] Exception type: Microsoft.Identity.Client.MsalClientException
, ErrorCode: authentication_canceled

   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.VerifyAuthorizationResult(AuthorizationResult authorizationResult, String originalState)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI webUi, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
```

Network logs:
Only a single call shows up in Fiddler:
```
GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2Fmycompany.com%2Foauth2%2Fv2.0%2Fauthorize HTTP/1.1
Host: login.microsoftonline.com
x-client-SKU: MSAL.NetCore
x-client-Ver: 4.40.0.0
x-client-CPU: x64
x-client-OS: Microsoft Windows 10.0.19043
client-request-id: 45b150d5-1a24-40e3-9ef7-34c222243a9f
return-client-request-id: true
x-app-name: UnknownClient
x-app-ver: 0.0.0.0
Accept: application/json

HTTP/1.1 200 OK
Cache-Control: max-age=86400, private
Content-Type: application/json; charset=utf-8
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 45b150d5-1a24-40e3-9ef7-34c222243a9f
x-ms-request-id: 4a29d2a8-e878-492f-bcd1-8fbbb2fc0900
x-ms-ests-server: 2.1.12470.11 - NCUS ProdSlices
Set-Cookie: fpc=Av2_xxx; expires=Thu, 17-Mar-2022 14:40:12 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: esctx=AQABAAAAAAD--xxx; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; httponly
Date: Tue, 15 Feb 2022 14:40:12 GMT
Content-Length: 956

{"tenant_discovery_endpoint":"https://login.microsoftonline.com/nussbaum.com/v2.0/.well-known/openid-configuration","api-version":"1.1","metadata":[{"preferred_network":"login.microsoftonline.com","preferred_cache":"login.windows.net","aliases":["login.microsoftonline.com","login.windows.net","login.microsoft.com","sts.windows.net"]},{"preferred_network":"login.partner.microsoftonline.cn","preferred_cache":"login.partner.microsoftonline.cn","aliases":["login.partner.microsoftonline.cn","login.chinacloudapi.cn"]},{"preferred_network":"login.microsoftonline.de","preferred_cache":"login.microsoftonline.de","aliases":["login.microsoftonline.de"]},{"preferred_network":"login.microsoftonline.us","preferred_cache":"login.microsoftonline.us","aliases":["login.microsoftonline.us","login.usgovcloudapi.net"]},{"preferred_network":"login-us.microsoftonline.com","preferred_cache":"login-us.microsoftonline.com","aliases":["login-us.microsoftonline.com"]}]}
```

**Comment by trwalke** [comment]
@neha-bhargava do you think this may be related to the recent changes made with the browser?

**Comment by bvirkler** [comment]
I don't have any proof of this, but I'm pretty sure it was working a week or two ago.  I got the latest WebView2 runtime on Feb 13 so I wondered if that was the cause, but I couldn't find a way to downgrade it and test.

**Comment by bgavrilMS** [comment]
@trwalke - I don't think Neha's changes are related to this. Can you repro the problem with WebView2?
@bvirkler - can you repro this every time now? It might be that WebView2 runtime has a problem, but as you say, you cannot downgrade. 

@bvirkler - have you considered using WAM? https://aks.ms/msal-net-wam
