### ISSUE TITLE
[Bug] Microsoft.IdentityModel.S2S.S2SAuthenticationException: S2S50001: Exception caught while creating S2SAuthenticationManager. Exception: S2S40008: 'Microsoft.IdentityModel.S2S.Configuration.S2SAuthenticationManagerFactory' caught exceptions when loading the certificate. Exception : 'SharedTokenCacheCredential authentication failed: Persistence check failed. Inspect inner exception for details'

### ISSUE THREAD

**Issue by xubinzheng** [AzureAD/microsoft-authentication-library-for-dotnet#3238]
**Logs and network traces**
```
Microsoft.IdentityModel.S2S.S2SAuthenticationException: S2S50001: Exception caught while creating S2SAuthenticationManager. Exception: S2S40008: 'Microsoft.IdentityModel.S2S.Configuration.S2SAuthenticationManagerFactory' caught exceptions when loading the certificate. Exception : 'SharedTokenCacheCredential authentication failed: Persistence check failed. Inspect inner exception for details'
   at Microsoft.IdentityModel.S2S.Extensions.AspNetCore.S2SAuthenticationExtensions.<>c__DisplayClass15_0.<AddS2SAuthentication>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.Extensions.DependencyInjection.CommonAppBuilderExtensions.<>c__DisplayClass0_0.<<UseSpaRoutes>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MyApps.Startup.<>c.<<Configure>b__8_2>d.MoveNext() in /source/src/Microsoft.AzureAd.MyApps/Startup.cs:line 701
--- End of stack trace from previous location where exception was thrown ---
   at MyApps.Startup.<>c.<<Configure>b__8_1>d.MoveNext() in /source/src/Microsoft.AzureAd.MyApps/Startup.cs:line 694
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at MyApps.Startup.<>c.<<Configure>b__8_0>d.MoveNext() in /source/src/Microsoft.AzureAd.MyApps/Startup.cs:line 672
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Which version of MSAL.NET are you using?**
Microsoft.Identity.ServiceEssentials.Extensions.AspNetCoreMiddleware.S2S Version="1.4.0"
Microsoft.Identity.ServiceEssentials.AspNetCore Version="1.7.0"
Microsoft.Identity.Web.UI Version="1.15.0"

**Platform**
Ubuntu 18.04 (in Kubernetes), .Net Core 3.1, C#

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [x] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

**Is this a new or existing app?**
a. The app is in production, and I have upgraded to a new version of MSAL.

**Repro**
Code in `startup.cs`
```
            services.AddMiseWithDefaultAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddDistributedTokenCaches();
```
Config in `appsettings.json`
```
    "ClientCertificates": [
      {
        "SourceType": "KeyVault",
        "KeyVaultUrl": "https://<KV name>.vault.azure.net/",
        "KeyVaultCertificateName": "<cert name>"
      }
    ],
    "TokenDecryptionCertificates": [
      {
        "SourceType": "KeyVault",
        "KeyVaultUrl": "https://<KV name>.vault.azure.net/",
        "KeyVaultCertificateName": "<cert name>"
      }
    ],
```

**Expected behavior**
A clear and concise description of the exception can help us to debug the issue. So far it looks like MISE cannot work with Azure KV in docker containers?

**Actual behavior**
exception is thrown

**Possible solution**

**Additional context / logs / screenshots / links to code**

Add any other context about the problem here, such as logs and screenshots, and even links to code.

**Comment by jmprieur** [comment]
@[xubinzheng](https://github.com/xubinzheng) this is an issue with SAL, not MSAL.NET
It's an access issue. You need to ensure you can access keyvault from the container.
Also the container doesn't contain MSI

**Comment by jmprieur** [comment]
Closing as this is not an MSAL.NET issue.
