### ISSUE TITLE
[Bug] Unable to get access token when password contains whitespace

### ISSUE THREAD

**Issue by huhubun** [AzureAD/microsoft-authentication-library-for-dotnet#3249]
**Logs and network traces**
```
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:53Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] MSAL MSAL.NetCore with assembly version '4.42.1.0'. CorrelationId(7b4d1ac2-c1f4-42b7-bb0b-105fe392254c)
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:53Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c]
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.microsoft.com/.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenByUsernamePassword
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c
UserAssertion set: False
LongRunningOboCacheKey set: False

MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:53Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] === Token Acquisition (UsernamePasswordRequest) started:
         Scopes: https://graph.microsoft.com/.default
        Authority Host: login.microsoftonline.com
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:53Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] [Region discovery] Not using a regional authority.
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:53Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Fetching instance discovery from the network from host login.microsoftonline.com.
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:54Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Authority validation enabled? True.
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:54Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Authority validation - is known env? True.
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:54Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Sending request to userrealm endpoint.
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:54Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c]
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:55Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Response status code does not indicate success: 400 (BadRequest).
MSAL Warning False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:55Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Request retry failed.
MSAL Info False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:55Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] HttpStatusCode: 400: BadRequest
MSAL Error False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:55Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
, ErrorCode: invalid_grant
HTTP StatusCode 400
CorrelationId 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c

MSAL Error False False MSAL 4.42.1.0 MSAL.NetCore .NET 6.0.3 Microsoft Windows 10.0.19044 [2022-03-26 04:35:55Z - 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
, ErrorCode: invalid_grant
HTTP StatusCode 400
CorrelationId 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c

   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
Unhandled exception. MSAL.NetCore.4.42.1.0.MsalUiRequiredException:
        ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS50126: Error validating credentials due to invalid username or password.
Trace ID: 5b0ce214-707d-47ad-bb0d-60e5b6460f01
Correlation ID: 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c
Timestamp: 2022-03-26 04:35:54Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByUsernamePasswordParameters usernamePasswordParameters, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\bill.nong\source\repos\dosometests\MicrosoftAuthenticationLibraryTest\Program.cs:line 27
   at Program.<Main>(String[] args)
        StatusCode: 400
        ResponseBody: {"error":"invalid_grant","error_description":"AADSTS50126: Error validating credentials due to invalid username or password.\r\nTrace ID: 5b0ce214-707d-47ad-bb0d-60e5b6460f01\r\nCorrelation ID: 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c\r\nTimestamp: 2022-03-26 04:35:54Z","error_codes":[50126],"timestamp":"2022-03-26 04:35:54Z","trace_id":"5b0ce214-707d-47ad-bb0d-60e5b6460f01","correlation_id":"7b4d1ac2-c1f4-42b7-bb0b-105fe392254c","error_uri":"https://login.microsoftonline.com/error?code=50126"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 7b4d1ac2-c1f4-42b7-bb0b-105fe392254c
x-ms-request-id: 5b0ce214-707d-47ad-bb0d-60e5b6460f01
x-ms-ests-server: 2.1.12559.10 - SEASLR1 ProdSlices
x-ms-clitelem: 1,50126,0,,
Set-Cookie: fpc=AhW9iW3s3lxEpI54rqy4feWVBSmBAQAAACqP0NkOAAAA; expires=Mon, 25-Apr-2022 04:35:54 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Sat, 26 Mar 2022 04:35:54 GMT
```

**Which version of MSAL.NET are you using?**
MSAL.NET 4.42.1.0

**Platform**
.NET 6

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [x] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?
N/A

**Is this a new or existing app?**
c. This is a new app or experiment.

**Repro**

```csharp
const string CLIENT_ID = "MY_CLIENT_ID";
const string TENANT_ID = "MY_TENANT_ID";
const string USERNAME = "MY_USERNAME";
const string PASSWORD = " MY_PASSWORD";

var secureString = new SecureString();
foreach (var c in PASSWORD)
{
    secureString.AppendChar(c);
}

var app = PublicClientApplicationBuilder.Create(CLIENT_ID)
    .WithAuthority(AzureCloudInstance.AzurePublic, TENANT_ID)
    .WithDefaultRedirectUri()
    .WithLogging(
        MyLoggingMethod,
        LogLevel.Info,
        enablePiiLogging: false,
        enableDefaultPlatformLogging: false)
    .Build();

var result = await app.AcquireTokenByUsernamePassword(
        new string[] { "https://graph.microsoft.com/.default" },
        USERNAME,
        secureString)
    .WithCorrelationId(Guid.NewGuid())
    .ExecuteAsync();

Console.WriteLine(result.AccessToken);

void MyLoggingMethod(LogLevel level, string message, bool containsPii)
{
    Console.WriteLine($"MSAL {level} {containsPii} {message}");
}
```

**Expected behavior**
If correct password starts or ends with ` `(whitespace), and `PASSWORD` equals correct password, should not return `AADSTS50126: Error validating credentials due to invalid username or password.`

**Actual behavior**
An `Microsoft.Identity.Client.MsalUiRequiredException` with message `AADSTS50126: Error validating credentials due to invalid username or password.` throws.

**Possible solution**
N/A

**Additional context / logs / screenshots / links to code**
I recently noticed that use https://admin.microsoft.com/ - Users - Active users - Reset password, and `https://graph.microsoft.com/v1.0/me/changePassword` API it is possible to set a password with whitespace.

So I set the password to the following cases where the password contains whitespace, and tried to get access token by MSAL.NET, but some cases got error message:
-  <code>&nbsp;password</code>, `password `,  <code>&nbsp;password&nbsp;</code>: whitespace appear at the beginning, end, or both of the password, will get error message `AADSTS50126: Error validating credentials due to invalid username or password.`
- `pass word`: whitespace appear in the middle of the password, that's fine

However, it is not a problem to access https://login.microsoftonline.com/ through a browser to sign in.

I'm not sure, is it a problem with my code, or library, or an inconsistency between different URLs at Microsoft?

Thanks

**Comment by bgavrilMS** [comment]
@huhubun - can't you just change the password to not include a space? We don't recommend to use this flow except for test scenarios, so you should have control over the password.

**Comment by bgavrilMS** [comment]
Please contact the AAD service via the Azure Portal about this. We do not recommend this flow.
