### ISSUE TITLE
[Bug] ArgumentNullException: keyBlob 

### ISSUE THREAD

**Issue by mezaugusto** [AzureAD/microsoft-authentication-library-for-dotnet#3324]
**Logs and network traces**
We have seen one instance of this happening, I can provide more logs internally.

```
False MSAL 4.42.0.0 MSAL.Desktop 4.7.2 Windows Server 2019 Datacenter [2022-05-16 12:46:15Z] (ConfidentialClient[certSubject:CN=***][clientId:***][redirectUri:]: 0.0.0.0) [Clear] Clearing access token cache data.
False MSAL 4.42.0.0 MSAL.Desktop 4.7.2 Windows Server 2019 Datacenter [2022-05-16 12:46:15Z] (ConfidentialClient[certSubject:CN=***][clientId:***][redirectUri:]: 0.0.0.0) [GetAllAccessTokens] Total number of cache partitions found while getting access tokens: 0
False MSAL 4.42.0.0 MSAL.Desktop 4.7.2 Windows Server 2019 Datacenter [2022-05-16 12:46:15Z - ***] (ConfidentialClient[certSubject:CN=***][clientId:***][redirectUri:]: 0.0.0.0) [FindAccessTokenAsync] Discovered 0 access tokens in cache using partition key: ***_AppTokenCache
[Warning]False MSAL 4.42.0.0 MSAL.Desktop 4.7.2 Windows Server 2019 Datacenter [2022-05-16 12:46:15Z - ***] (ConfidentialClient[certSubject:CN=***][clientId:***][redirectUri:]: 0.0.0.0) Request retry failed.
True MSAL 4.42.0.0 MSAL.Desktop 4.7.2 Windows Server 2019 Datacenter [2022-05-16 12:46:15Z -***] (ConfidentialClient[certSubject:CN=***][clientId:***][redirectUri:]: 0.0.0.0) System.ArgumentNullException: Value cannot be null.
Parameter name: keyBlob
   at System.Security.Cryptography.RSACryptoServiceProvider.IsPublic(Byte[] keyBlob)
   at System.Security.Cryptography.X509Certificates.PublicKey.get_Key()
   at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(X509Certificate2 certificate, String base64EncodedThumbprint, Boolean sendX5C)
   at Microsoft.Identity.Client.Internal.ClientCredential.CertificateAndClaimsClientCredential.AddConfidentialClientParametersAsync(OAuth2Client oAuth2Client, ICoreLogger logger, ICryptographyManager cryptographyManager, String clientId, String tokenEndpoint, Boolean sendX5C, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<AddBodyParamsAndHeadersAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendTokenRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<FetchNewAccessTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()</pii>
```

I see a related issue #2189 that was fixed in 4.25 release, and we are using a more recent version

**Which version of MSAL.NET are you using?**
MSAL.NET 4.42.0.0
Microsoft.Identity.Web.TokenCache 1.22.1

**Platform**
.NET Framework 4.6.2

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [x] Service to Service calls

**Is this a new or existing app?**

The app is in production, I haven't upgraded MSAL, but started seeing this issue.

**Repro**

Not being able to reproduce, server was healthy in terms of resources and RPS was normal (3.56 RPS)

simplified code:
```c#
var applicationOptions = new ConfidentialClientApplicationOptions
{
    ClientId = clientid,
    ClientName = clientName,
    LegacyCacheCompatibilityEnabled = false,
    EnableCacheSynchronization = false,
};

var client = ConfidentialClientApplicationBuilder
                .CreateWithApplicationOptions(applicationOptions)
                .WithAuthority(authority)
                .WithLogging(MsalClientLogger, logLevel: LogLevel.Warning, enablePiiLogging: true)
                .WithCertificate(certificate, sendX5C: true)
                .WithAzureRegion(azureRegion)
                .Build();

client.AddInMemoryTokenCache(services =>
{
    services.Configure<MemoryCacheOptions>(options =>
    {
        options.SizeLimit = cacheSizeLimitInMb * 1024 * 1024;
    });
});

client
    .AcquireTokenForClient(scopes)
    .WithCorrelationId(correlationId)
    .WithTenantId(tenantId);
```

**Expected behavior**
Getting token for resource

**Actual behavior**
Request failed, retry on different server succeeded, no restart was necessary, subsequent request to the failed server have been successful

**Comment by bgavrilMS** [comment]
Ack, this failure occurs when calling `PublicKey` on the cert. It looks like MSAL tries to see if cert size is at least 2k, but this should not be an SDK concern, the service should reject a non-secure cert. I'll disable the check. 

@mezaugusto - you should not be hitting this method super often, as tokens should be served from the cache first. Are you sure you're hitting the cache and not AAD ? https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnet

**Comment by mezaugusto** [comment]
@bgavrilMS Yes, we have only seen this failure once (out of 3M+ daily calls), also we analyze the TokenSource of the AuthenticationResult and roughly 80% are retrieved from the cache and 20% from AAD.
 
Thanks for the quick triage!
