### ISSUE TITLE
[Bug] Nightly build fails frequently due to unstable test

### ISSUE THREAD

**Issue by trwalke** [AzureAD/microsoft-authentication-library-for-dotnet#3396]
The test that seems to fail very frequently is [ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=925454&view=ms.vss-test-web.build-test-results-tab&runId=2086770&resultId=100149&paneView=debug)

error: Assert.IsTrue failed. Background refresh 2 did not execute.

Stack Trace:  at Microsoft.Identity.Test.Unit.PublicApiTests.RefreshInTests.ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async() in \tests\Microsoft.Identity.Test.Unit\PublicApiTests\RefreshInTests.cs:line 153
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

Logs Output:
Debug Trace:
Framework: .NET Core
Test started ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async
1. Setup an app with a token cache with one AT
1. Setup an app with a token cache with one AT
2. Configure AT so that it shows it needs to be refreshed
3. Configure AAD to respond with a 500 error
Test ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async adds an HttpMessageHandler for https://login.microsoftonline.com/common/discovery/instance
Test ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async adds an HttpMessageHandler for 
Test ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async adds an HttpMessageHandler for 
Test ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async dequeued a mock handler for https://login.microsoftonline.com/common/discovery/instance
Test ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async dequeued a mock handler for 
Test ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async dequeued a mock handler for 
Test ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async adds an HttpMessageHandler for 
Test finished ATS_NonExpired_NeedsRefresh_AADUnavailableResponse_Async
**Which version of MSAL.NET are you using?**
4.44.0

**Repro**
The test seems to fail randomly but does occur about 2-3 times a week during nightly builds.

**Comment by localden** [comment]
@trwalke @bgavrilMS is this still the case?
