### ISSUE TITLE
[Bug] Maui iOS doesn't work with MSAL - 'The application cannot access the iOS keychain'

### ISSUE THREAD

**Issue by DRAirey1** [AzureAD/microsoft-authentication-library-for-dotnet#3636]
**Which version of MSAL.NET are you using?**
Microsoft.Identity.Client 4.46.0 - preview2
Microsoft.Identity.Client.Extensions.Msal  2.22.0

**Platform**
.net MAUI targeting iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive
    * [ ] Integrated Windows Authentication
    * [X ] Username Password
    * [ ] Device code flow (browserless)

**Is this a new or existing app?**
The app is in working in pre-production in XAMARIN, and I have upgraded to a new version of Maui and MSAL.

**Repro**

```
<plist version="1.0">
  <dict>
    <key>keychain-access-groups</key>
    <array>
       <string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
    </array>
  </dict>
</plist>
```

**Expected behavior**
When running the iOS application in the simulator, I expect it to find the profile and fill in the $(AppIdentifierPrefix) macro. 

**Actual behavior**
The application doesn't appear to recognize the provision file settings in the project file:

```
  <PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Distribution: My Company, Inc. (1BR42YBHJD)</CodesignKey>
    <CodesignProvision>OpenBook Demo Ad Hoc</CodesignProvision>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net6.0-ios' and '$(Configuration)' == 'Debug'">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignKey>Apple Development: Barney Rubble (5QQCH53X5G)</CodesignKey>
    <CodesignProvision>OpenBook Demo Development</CodesignProvision>
  </PropertyGroup>
```

and it throws this compile-time warning:

`warning : Cannot expand $(AppIdentifierPrefix) in Entitlements.plist without a provisioning profile.
`

And then takes an exception when executing this code:

```
    var authenticationResult = await this.signInApplication
    .AcquireTokenByUsernamePassword(this.Scopes, this.UserName, securePassword)
    .ExecuteAsync(cancellationToken);
```

```
Microsoft.Identity.Client.MsalClientException
  Message=The application does not have keychain access groups enabled in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group 'com.com.microsoft.adalcache' is not enabled in the Entitlements.plist. Also, use the WithIosKeychainSecurityGroup api to set the keychain access group. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups and entitlements.
```

**Possible solution**
Hard-coding the TeamID into the 'Entitlements.plist' appears to work around the problem:

```
<plist version="1.0">
  <dict>
    <key>keychain-access-groups</key>
    <array>
      <string>3BS38KBMFL.com.microsoft.adalcache</string>
    </array>
  </dict>
</plist>
```

**Additional context / logs / screenshots / links to code**
Working with Visual Studio 2022 Version 17.3.1
Debug with iOS Simulator - iPhone 13 iOS 15.5

**Comment by DRAirey1** [comment]
To anyone having this problem, Visual Studio has a UI that manages the 'Entitlements.plist' file. Select the Maui project, select Properties->IOS->Bundle Signing->Custom Entitlements. From here, you select the 'Entitlements.plist' from your Platforms->iOS directory. This will add a bunch of entries to your project file that looks like this:

```
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0-android|AnyCPU'">
    <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0-android|AnyCPU'">
    <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Local|net6.0-android|AnyCPU'">
    <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
  </PropertyGroup>
```
Now the build will find the Entitlements, replace the macros and build correctly.

**Comment by bgavrilMS** [comment]
Thanks for pointing it out @DRAirey1, i'll get the docs updated with troubleshooting step.

**Comment by Ruvi1996** [comment]
@DRAirey1  After doing this I still get the same error. Not only in my project.  [The sample](https://github.com/Azure-Samples/active-directory-xamarin-native-v2) given in Azure-Samples repository is also getting this error. That sample also didn't have entries you have mentioned above so I added them. But still getting that same error on that project too.

Here is the error (this is from the MauiB2C project from the sample mentioned above even after adding the CodesEntitlements entries): 

```
ObjCRuntime.ObjCException
  Message=Objective-C exception thrown.  Name: Microsoft.Identity.Client.MsalClientException Reason: The application does not have keychain access groups enabled in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group 'com.com.microsoft.adalcache' is not enabled in the Entitlements.plist. Also, use the WithIosKeychainSecurityGroup api to set the keychain access group. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups and entitlements. (Microsoft.Identity.Client.MsalClientException)
   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.Save(IiOSKey key, String payload)
   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.SaveAccessToken(MsalAccessTokenCacheItem item)
   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheInternal.SaveTokenResponseAsync(AuthenticationRequestParameters requestParams, MsalTokenResponse response)
   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheInternal.SaveTokenResponseAsync(AuthenticationRequestParameters requestParams, MsalTokenResponse response)
   at Microsoft.Identity.Client.Cache.CacheSessionManager.SaveTokenResponseAsync(MsalTokenResponse tokenResponse)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.CacheTokenResponseAndCreateAuthenticationResultAsync(MsalTokenResponse msalTokenResponse)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at MauiB2C.MSALClient.PCAWrapperB2C.AcquireTokenInteractiveAsync(String[] scopes) in C:\Users\RuvindraSenevirathne\source\repos\active-directory-xamarin-native-v2\MAUI\MauiAppB2C\MSALClient\PCAWrapperB2C.cs:line 65
   at MauiB2C.MainPage.OnSignInClicked(Object sender, EventArgs e) in C:\Users\RuvindraSenevirathne\source\repos\active-directory-xamarin-native-v2\MAUI\MauiAppB2C\MainPage.xaml.cs:line 32
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply()

Native stack trace:
	0   CoreFoundation                      0x0000000110314604 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000011d254a45 objc_exception_throw + 48
	2   libxamarin-dotnet-debug.dylib       0x000000010bd8addf xamarin_process_managed_exception + 943
	3   MauiB2C                             0x0000000102d65c19 _ZL31native_to_managed_trampoline_10P11objc_objectP13objc_selectorPP11_MonoMethodj + 361
	4   MauiB2C                             0x0000000102d663f9 -[__MonoMac_NSAsyncSynchronizationContextDispatcher xamarinApplySelector] + 41
	5   Foundation                          0x00000001133055d7 __NSThreadPerformPerform + 179
	6   CoreFoundation                      0x00000001102814a7 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x000000011028139f __CFRunLoopDoSource0 + 180
	8   CoreFoundation                      0x000000011028086c __CFRunLoopDoSources0 + 242
	9   CoreFoundation                      0x000000011027af68 __CFRunLoopRun + 871
	10  CoreFoundation                      0x000000011027a704 CFRunLoopRunSpecific + 562
	11  GraphicsServices                    0x000000011e563c8e GSEventRunModal + 139
	12  UIKitCore                           0x0000000128b5665a -[UIApplication _run] + 928
	13  UIKitCore                           0x0000000128b5b2b5 UIApplicationMain + 101
	14  libmonosgen-2.0.dylib               0x000000010c578aa2 do_icall + 194
	15  libmonosgen-2.0.dylib               0x000000010c577abd do_icall_wrapper + 253
	16  libmonosgen-2.0.dylib               0x000000010c569cda interp_exec_method + 2970
	17  libmonosgen-2.0.dylib               0x000000010c567f5f interp_runtime_invoke + 239
	18  libmonosgen-2.0.dylib               0x000000010c45fbab mono_jit_runtime_invoke + 1227
	19  libmonosgen-2.0.dylib               0x000000010c382198 mono_runtime_invoke_checked + 136
	20  libmonosgen-2.0.dylib               0x000000010c388f3b mono_runtime_exec_main_checked + 107
	21  libmonosgen-2.0.dylib               0x000000010c4c2042 mono_jit_exec + 354
	22  libxamarin-dotnet-debug.dylib       0x000000010bd9ee9d xamarin_main + 1949
	23  MauiB2C                             0x0000000102df7844 main + 52
	24  dyld                                0x000000010b972f21 start_sim + 10
	25  ???                                 0x000000020340452e 0x0 + 8644478254
	26  ???                                 0x0000000000000003 0x0 + 3

  Source=Microsoft.iOS
  StackTrace:
   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns_exception)
   at ObjCRuntime.Runtime.throw_ns_exception(IntPtr exc)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiB2C.Program.Main(String[] args) in C:\Users\RuvindraSenevirathne\source\repos\active-directory-xamarin-native-v2\MAUI\MauiAppB2C\Platforms\iOS\Program.cs:line 15

```

**Comment by chuckgiddens** [comment]
Support for iOS is really lite in Maui.  I only have iOS users and this is very disappointing.
