### ISSUE TITLE
[Bug] MsalClientException: ErrorCode: authentication_canceled even though it was not canceled.

### ISSUE THREAD

**Issue by shivam1305** [AzureAD/microsoft-authentication-library-for-dotnet#3638]
**Description**
We use below code to AquireTokenInteractive with Prompt to select the user.
```
 authResult = await this.publicClientApp.AcquireTokenInteractive(Scopes)
                        .WithAuthority(AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount)
                        .WithPrompt(Microsoft.Identity.Client.Prompt.SelectAccount)
                        .ExecuteAsync().ConfigureAwait(false);
```

and we are getting below popup to select User for account.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/42907325/187129693-8d1385f7-4c3e-493d-87b2-6433a5a4e57b.png">

When we select Microsoft account then it automatically close the pop up and giving the below error 
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/42907325/187129746-ac13b2a6-8212-452b-b102-bda0165154b7.png">

**Which version of MSAL.NET are you using?**
MSAL.NET 4.24.0, 4.46.0 and 4.46.1

**Platform**
UWP

**Expected behavior**
When we click on Microsoft account highlighted below:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/42907325/187132574-34de0d03-d973-45d0-aef6-e7cefe21f590.png">

It should allow us to sign in with personal account.

**Actual behavior**
It is throwing MsalClientException:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/42907325/187131890-112e8549-d6ad-4f73-88c4-95dd170ef203.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/42907325/187131934-7b78199b-8e07-4f52-a3cd-cab74f463ac6.png">

   at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamAdapters.CreateMsalResponseFromWamResponse(IWebTokenRequestResultWrapper wamResponse, IWamPlugin wamPlugin, String clientId, ILoggerAdapter logger, Boolean isInteractive)
   at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.<AcquireInteractiveWithPickerAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.<AcquireTokenInteractiveAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.<FetchTokensAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<FetchTokensFromBrokerAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CompactTicket.MainPage.<OnSignInClicked>d__6.MoveNext() in C:\Work\Corleone\investigation\Demo\CompactTicket\CompactTicket\MainPage.xaml.cs:line 66

Please let me know if you need more information.

**Comment by bgavrilMS** [comment]
I can repro this.

**Comment by bgavrilMS** [comment]
So, I was able to repro this a few times, and then it stopped repro-ing. It seems to be an issue with WAM itself, because MSAL constructs the correct request, but then WAM just errors out saying "User Cancelled". 

Can you please follow the instructions here to get a repro and open a ticket with WAM? https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging#windows-broker-wam-logging

**Comment by SameerK-MSFT** [comment]
Investigation shows that this is not related to MSAL.NET. Closing it.
