### ISSUE TITLE
[Bug] A default account was not found. High auth failure rate with MSAL update 4.46.2!

### ISSUE THREAD

**Issue by NakulSabharwal** [AzureAD/microsoft-authentication-library-for-dotnet#3787]
**Logs and network traces**
```
"Payload_ErrorMessage": A default account was not found,
"Payload_ErrorLocation":    at Microsoft.Identity.Client.Platforms.Features.WamBroker.WamBroker.<AcquireTokenSilentDefaultUserAsync>d__28.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.<SendTokenRequestToBrokerAsync>d__10.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.<ExecuteAsync>d__9.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.<ExecuteAsync>d__5.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.<ExecuteAsync>d__2.MoveNext()

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

**Which version of MSAL.NET are you using?**
MSAL.NET 4.46.2

**Platform**
.NET Framework 4.7

**What authentication flow has the issue?**
* Desktop
    * Integrated Windows Authentication (WAM)

Other?
User is not able to login on a production app with multiple retries. We are seeing very high failure auth rate.

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL. We are seeing very high auth failure rate in public production app, treat it as P0.

**Repro**
Update to below MSAL configurations to repro this issue

```xml
<PackageReference Include="Microsoft.Identity.Client">
<Version>4.46.2</Version>
</PackageReference>
<PackageReference Include="Microsoft.Identity.Client.Desktop">
<Version>4.46.2</Version>
</PackageReference>
<PackageReference Include="Microsoft.Identity.Client.Extensions.Msal">
<Version>2.23.0</Version>
```
**Expected behavior**
User should be able to login successfully.

**Actual behavior**
User is not able to login even with multiple retries and getting this error. We are seeing very high auth failure rate, treat it as P0.

**Comment by bgavrilMS** [comment]
@NakulSabharwal - if this is problem you found in production, please revert to a working version of MSAL to migiagte the issue. The team does not handle P0 bugs.

Can you please give more details - what is the code that was working and is not working now?

**Comment by techyrajeev** [comment]
We just updated to MSAL version from below config to 
```xml
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Client">
      <Version>4.44.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Client.Desktop">
      <Version>4.44.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal">
      <Version>2.20.1</Version>
    </PackageReference>
    
    
   to this version
    
   
       <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Client">
      <Version>4.46.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Client.Desktop">
      <Version>4.46.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal">
      <Version>2.23.0</Version>
    </PackageReference>
    ```

**Comment by techyrajeev** [comment]
This is the way we create public client app
```            return PublicClientApplicationBuilder.Create(clientId)
                  .WithDefaultRedirectUri()
                  .WithAuthority(authority, tenant)
                  .WithWindowsBroker()
                  .WithMsalLogging();
```

**Comment by NakulSabharwal** [comment]
@bgavrilMS Do you know when this error is thrown? and why its coming only in version MSAL 4.46.2 and not in previous versions?

**Comment by bgavrilMS** [comment]
Please move to new broker, we are not fixing issues in old broker.
