### ISSUE TITLE
[Bug] MissingMethodException due to forced WAM upgrade

### ISSUE THREAD

**Issue by azchohfi** [AzureAD/microsoft-authentication-library-for-dotnet#3964]
**Logs and network traces**
```
System.MissingMethodException: Method not found: 'Void Microsoft.Identity.Client.Core.MsalLoggerExtensions.Verbose(Microsoft.Identity.Client.Core.ILoggerAdapter, System.String)'.
   at Microsoft.Identity.Client.Broker.RuntimeBroker.IsBrokerInstalledAndInvokable(AuthorityType authorityType)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsFromBrokerAsync(String homeAccountIdFilter, ICacheSessionManager cacheSessionManager, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsInternalAsync(ApiIds apiId, String homeAccountIdFilter, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync()
```

**Which version of MSAL.NET are you using?**
MSAL.NET 4.50.0

**Platform**
net7.0

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of MSAL.

**Repro**

```csharp
var app = PublicClientApplicationBuilder
    .Create(ClientId)
    .WithDefaultRedirectUri()
    .WithBrokerPreview()
    .WithParentActivityOrWindow(....)
    .Build();
var accounts = await app.GetAccountsAsync();
```

**Expected behavior**
Works just like in 0.49.1.

**Actual behavior**
Throws MissingMethodException.

**Comment by pmaytak** [comment]
I can't repro this. Do you reference Microsoft.Identity.Client.NativeInterop? Can you make sure to explicitly reference 0.13.5?

**Comment by bgavrilMS** [comment]
That's most likely the case. You upgraded MSAL but didn't upgrade the NativeInterop package. 

@pmaytak  In hindsight, relying on `InternalsVisibleTo` will make it impossible to detect "actual public api" changes in NativeInterop package. I wonder if we can improve the supportability / error message here?

**Comment by azchohfi** [comment]
I see what the problem was.
I went to VS and updated all my packages to the latest available versions, but, by default, VS does that only for stable packages, not for the preview ones, so it only updated Microsoft.Identity.Client from 4.49.1 to 4.50.0 and Microsoft.Identity.Client.Extensions.Msal from 2.25.3 to 2.26.0. It did not update Microsoft.Identity.Client.Broker from 4.49.1-preview to 4.50.0-preview.
Still, after updating to the latest, I get a different exception:
```
Unhandled exception: MSAL.NetCore.4.50.0.0.MsalClientException:
        ErrorCode: wam_runtime_init_failed
Microsoft.Identity.Client.MsalClientException: Unable to load DLL 'msalruntime' or one of its dependencies: The specified module could not be found. (0x8007007E) See https://aka.ms/msal-net-wam#troubleshooting
 ---> System.DllNotFoundException: Unable to load DLL 'msalruntime' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Microsoft.Identity.Client.NativeInterop.API.x64.MSALRUNTIME_Startup()
   at Microsoft.Identity.Client.NativeInterop.API.x64.Startup()
   at Microsoft.Identity.Client.NativeInterop.Module.AddRef(String handleName)
   at Microsoft.Identity.Client.NativeInterop.Core..ctor()
   at Microsoft.Identity.Client.Broker.RuntimeBroker.<>c.<.cctor>b__24_0()
   --- End of inner exception stack trace ---
   at Microsoft.Identity.Client.Broker.RuntimeBroker.<>c.<.cctor>b__24_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Identity.Client.Broker.RuntimeBroker.IsBrokerInstalledAndInvokable(AuthorityType authorityType)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsFromBrokerAsync(String homeAccountIdFilter, ICacheSessionManager cacheSessionManager, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsInternalAsync(ApiIds apiId, String homeAccountIdFilter, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync()
```
I've looked at the source of that package, and I only see a build folder, not a buildTransitive. That is probably why the need of a manual installation is needed. I believe this should be addressed.

I also agree with @bgavrilMS, the `InternalsVisibleTo` is makes it impossible to detect breaking changes, but this could/should also be solved at a NuGet level. The new package has a binary incompatibility with the previous version, so in semver that would mean a major version bump. The package should have a dependency on a specific major version, with an upper bound.

**Comment by bgavrilMS** [comment]
CC @gladjohn for the native DLL not found exception - I believe there is a workaround. I think we need to fix this before GA-ing WAM broker.

**Comment by gladjohn** [comment]
@azchohfi Are you testing this for the MSIX packaging in NETFX? in MSAL 4.50.0 we fixed the packaging issue, you need to add a reference to the Interop in your WapProj

**Comment by azchohfi** [comment]
Nop, that is not the case here. This is a net7.0-windows10.0.17763.0 application.
I will do that eventually but haven't tried it yet.

**Comment by pmaytak** [comment]
> That's most likely the case. You upgraded MSAL but didn't upgrade the NativeInterop package.
> 
> @pmaytak In hindsight, relying on `InternalsVisibleTo` will make it impossible to detect "actual public api" changes in NativeInterop package. I wonder if we can improve the supportability / error message here?

Hmm, well we rely a lot on internals, so can't remove `InternalsVisibleTo`. Somehow globally catching MissingMethodEx and retrowing may not be accurate. Not sure what proper way to do this would be. Once the fix for packaging goes in the next release, that should reduce these errors, since Interop will be loaded automatically.
