### ISSUE TITLE
[Bug] WinHttpHandler not working as HttpClientHandler for MSAL.NET

### ISSUE THREAD

**Issue by lgiuliani80** [AzureAD/microsoft-authentication-library-for-dotnet#4061]
**Logs and network traces**
```
Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.WinHttpException (80070057, 87): Error 87 calling WinHttpAddRequestHeaders, 'Parametro non corretto.'.
   at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError(String nameOfCalledFunction)
   at System.Net.Http.WinHttpHandler.AddRequestHeaders(SafeWinHttpHandle requestHandle, HttpRequestMessage requestMessage, CookieContainer cookies, DecompressionMethods manuallyProcessedDecompressionMethods)
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method, ILoggerAdapter logger, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Http.HttpManager.ExecuteWithRetryAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method, ILoggerAdapter logger, Boolean doNotThrow, Boolean retry, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Http.HttpManager.SendGetAsync(Uri endpoint, IDictionary`2 headers, ILoggerAdapter logger, Boolean retry, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.DiscoverAadInstanceAsync(Uri endpoint, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.SendInstanceDiscoveryRequestAsync(Uri authority, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.FetchAllDiscoveryMetadataAsync(Uri authority, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.GetMetadataAsync(Uri authority, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.FetchNetworkMetadataOrFallbackAsync(RequestContext requestContext, Uri authorityUri)
   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.GetMetadataEntryAsync(AuthorityInfo authorityInfo, RequestContext requestContext, Boolean forceValidation)
   at Microsoft.Identity.Client.Instance.AuthorityManager.RunInstanceDiscoveryAndValidationAsync()
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByUsernamePasswordParameters usernamePasswordParameters, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Sviluppo\CSharp\TestBugWinHttpHandlerGraph\TestBugWinHttpHandlerGraph\Program.cs:line 13
   at Program.<Main>(String[] args)
```

**Which version of MSAL.NET are you using?**
MSAL.NET 5.52.0

**Platform**
.NET Core 6

**What authentication flow has the issue?**
All flows (the issues is related to HttpClient)

**Is this a new or existing app?**
This is a new app or experiment.

**Repro**

```cs
using Microsoft.Identity.Client;

const string applicationId = "...omissis...";
const string tenantId = "...omissis...";

var app = PublicClientApplicationBuilder.Create(applicationId)
    .WithHttpClientFactory(new WinHttpMsalHttpClientFactory())
    .WithTenantId(tenantId)
    .Build();

var token = await app.AcquireTokenByUsernamePassword(
    new string[] { "https://graph.microsoft.com/.default" }, 
    "...omissis...", "...omissis...")
    .ExecuteAsync();

Console.WriteLine(token.AccessToken);

internal class WinHttpMsalHttpClientFactory : IMsalHttpClientFactory
{
    public HttpClient GetHttpClient()
    {
        if (OperatingSystem.IsWindows())
            return new HttpClient(handler: new WinHttpHandler(), true);
        else
            return new HttpClient();
    }
}
```

`MyProject.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.52.0" />
    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="7.0.0" />
  </ItemGroup>
</Project>
```

**Expected behavior**
The HttpRequest should succeed and use WinHttpHandler (WinInet) as HttpClientHandler.

**Actual behavior**
The exception reported above is triggered.

**Possible solution**
WinHttpAddRequestHeaders is apparently called with wrong parameters. It COULD be due to internal issues in **System.Net.Http.WinHttpHandler** as well.

**Notes**
- Problem introduced after version 4.39.0 of Microsoft.Identity.Client or version 6.0.1 of System.Net.Http.WinHttpHandler NuGet packages.
- Replaces https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1799 as this bug actually affects MSAL.NET (and/or System.Net.WinHttpHandler).

**Comment by lgiuliani80** [comment]
Quoting the documentation from WinHttpAddRequestHeaders Win32 API:

> If an invalid header is used, this function fails and [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror) returns [ERROR_INVALID_PARAMETER](https://learn.microsoft.com/en-us/windows/desktop/WinHttp/error-messages). The invalid header is not added.

This is the error we get, so apparently at least one of the headers passed by MSAL.NET are not considered valid by WinHttp Win32 APIs.

**Comment by bgavrilMS** [comment]
I would think this is a bug in WinHttpHandler ?

**Comment by bgavrilMS** [comment]
Thanks for following up @lgiuliani80 !
