### ISSUE TITLE
[Engineering Task] Identify flaky tests

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#4223]
Identify flaky tests

**Comment by gladjohn** [comment]
Issue 1 : https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1134116&view=logs&j=b518b04f-6c84-5938-67f2-8f2b5bcbaf6d&t=0830723a-193d-5b94-98f1-9af1d01f80b3

```
Run unit tests (NET6-WIN)
Failed AcquireTokenUnSuccessfulTelemetryTestAsync [29 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<0>. Actual:<1>. All mocks should have been consumed. Remaining mocks are for: 
  Stack Trace:
     at Microsoft.Identity.Test.Common.Core.Mocks.MockHttpManager.Dispose() in D:\a\1\s\tests\Microsoft.Identity.Test.Common\Core\Mocks\MockHttpManager.cs:line 63
   at Microsoft.Identity.Test.Common.Core.Mocks.MockHttpAndServiceBundle.Dispose() in D:\a\1\s\tests\Microsoft.Identity.Test.Common\Core\Mocks\MockHttpAndServiceBundle.cs:line 46
   at Microsoft.Identity.Test.Unit.PublicApiTests.TelemetryClientTests.AcquireTokenUnSuccessfulTelemetryTestAsync() in D:\a\1\s\tests\Microsoft.Identity.Test.Unit\PublicApiTests\TelemetryClientTests.cs:line 449
  Standard Output Messages:

```

**Comment by bgavrilMS** [comment]
For the issue above, the fix is here: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4089/files#diff-b3691898c1d74433b3217d813d8c823c3babe9dcfbf35a7c420757afbb5c84b6L435

**Comment by bgavrilMS** [comment]
Too broad, needs a spec. ADO does identify "flaky" tests btw.
