### ISSUE TITLE
[Bug] The browser-based authentication dialog cannot pop up after upgrading windows 11

### ISSUE THREAD

**Issue by huanwang111** [AzureAD/microsoft-authentication-library-for-dotnet#4351]
### Library version used

4.37.0

### .NET version

.Net Framework 4.6.2

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

Our products uses MSAL to get the token and a browser based authentication dialog is used. We did not change the library on the product, but recently we observed that dialog cannot render correctly on Windows 11. The issue happens from Aug, 2023.

The pop up dialog shows as empty dialog like below.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/43128677/94b1c781-11ea-49ab-8c9c-8e533bd3586d)

Sample log is attached.
Reason: The server or proxy was not found. 
Reason: The server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfill the request.

Microsoft.Identity.Client.MsalClientException: The browser based authentication dialog failed to complete. Reason: **The server or proxy was not found.** 
   at Microsoft.Identity.Client.Platforms.Features.WinFormsLegacyWebUi.WebUI.<AcquireAuthorizationAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceInternalAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.<FetchAuthCodeAndPkceVerifierAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()

### Relevant code snippets

```csharp
this.app = PublicClientApplicationBuilder.CreateWithApplicationOptions(new PublicClientApplicationOptions()
	{
		ClientId = AADContext.appId,
		LegacyCacheCompatibilityEnabled = true,
	}).WithAuthority(Endpoints.Instance.Auth)
	.WithRedirectUri(AADContext.RedirectUri.ToString())
	.Build();

IEnumerable<IAccount> exstingCount = this.app.GetAccountsAsync().Result;
return new AADAuthToken(this.app.AcquireTokenSilent(scopes, exstingCount.FirstOrDefault()).ExecuteAsync().Result);
```

### Expected behavior

We expect the popup window should render correctly and the users can perform login from the dialog.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

Seems a regression as the error is observed from Aug, 2023.

### Solution and workarounds

N/A

**Comment by gladjohn** [comment]
This issue may occur if your proxy server is not allowing to connect to the internet or the proxy settings are not configured correctly. Also, can you please upgrade to the latest version of MSAL? 4.37.0 is very old.

you can also take a look at [our docs](https://learn.microsoft.com/entra/msal/dotnet/advanced/httpclient) that describes some possible solutions - you can try passing a custom HttpClientFactory that sets up proxy settings.
