### ISSUE TITLE
[Bug] WAM not opening with "authentication_canceled" error on an elevated Excel VSTO Add-in app

### ISSUE THREAD

**Issue by maheshdevaraju** [AzureAD/microsoft-authentication-library-for-dotnet#4360]
### Library version used

4.56.0

### .NET version

.NET Framework 4.8

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

I have created a C# Excel VSTO Add-in application, with a Login button in the Ribbon. On clicking the Login button WAM dialog should appear. The app shows the WAM dialog without any issues when it is not elevated, but when the App is elevated I face the "authentication_canceled" error.

Repro Steps:
1. Create a new C# Excel VSTO Add-in project.
2. Add a ribbon component and add a button to it.
3. On ButtonClick call this method
```c#
        private async Task LogIn()
        {
            ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            var hWnd = (IntPtr)Globals.ThisAddIn.Application.Hwnd;
            var scopes = new[] { "User.Read" };

            IPublicClientApplication app =
                PublicClientApplicationBuilder.Create("Client-Id")
                    .WithDefaultRedirectUri()
                    .WithBroker(new BrokerOptions(BrokerOptions.OperatingSystems.Windows))
                    .Build();
            AuthenticationResult result = null;

            // Try to use the previously signed-in account from the cache
            IEnumerable<IAccount> accounts = await app.GetAccountsAsync();
            IAccount existingAccount = accounts.FirstOrDefault();

            try
            {
                if (existingAccount != null)
                {
                    result = await app.AcquireTokenSilent(scopes, existingAccount).ExecuteAsync();
                }
                // Next, try to sign in silently with the account that the user is signed into Windows
                else
                {
                    result = await app.AcquireTokenSilent(scopes, PublicClientApplication.OperatingSystemAccount)
                        .ExecuteAsync();
                }
            }
            // Can't get a token silently, go interactive
            catch (MsalUiRequiredException ex)
            {
                try
                {
                    result = await app.AcquireTokenInteractive(scopes)
                        .WithParentActivityOrWindow(hWnd)
                        .ExecuteAsync();
                }
                catch (MsalClientException exception)
                {
                    Console.WriteLine(exception);
                }
            }
        }
```

MsalClientException Message: 
User canceled authentication. 

StackTrace:
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<SignInInteractivelyAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<AcquireTokenInteractiveAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.<FetchTokensAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<FetchTokensFromBrokerAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ExcelAddIn3.Ribbon1.<LogInTest>d__2.MoveNext() in C:\Users\6118003\source\repos\ExcelAddIn3\ExcelAddIn3\Ribbon1.cs:line 65

### Expected behavior

The WAM dialog should be shown

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by maheshdevaraju** [comment]
Any updates on this bug? Was anyone able to reproduce it?

**Comment by JoshTefay** [comment]
I see this exact issue when using MSAL with the WAM Broker from a .NET Framework 4.8 WPF application. I have created a repro project here: https://github.com/JoshTefay/MsalBrokerWpfRepro
