### ISSUE TITLE
[Bug] Crash on iOS with MAUI when cancelling confirmation popup twice

### ISSUE THREAD

**Issue by arkadiuszokon** [AzureAD/microsoft-authentication-library-for-dotnet#4415]
### Library version used

4.57

### .NET version

DotnetVersion: 8.0.0-rc.2.23479.6
MauiVersion: 8.0.0-rc.2.9373

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

When starting authentication on iOS inside MAUI app - confirmation window from ASWebAuthenticationSession appears:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/2082525/7949befd-824f-43ad-8dc3-732caa6bde3a)
When clicking Cancel, starting auth again and clicking cancel again - application crashing with this exception:

`System.InvalidOperationException: Window was already activated
   at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Activated()
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_3(UIApplication app)
   at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass14_0.<OnActivated>b__0(OnActivated del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnActivated](IServiceProvider services, Action1 action)
   at Microsoft.Maui.MauiUIApplicationDelegate.OnActivated(UIApplication application)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)` 

looks like something is wrong in releasing auth session and old popup is still existing in UIApplication.Windows:
<img width="811" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/2082525/5c67106c-cfcd-4dd9-8201-dfb97b587d0e">

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Seems like a generic error @arkadiuszokon , not one related to MSAL? MSAL is the identity SDK for Microsoft Entra (Azure Active Directory).
