### ISSUE TITLE
[Bug] MsalCachePersistence issue while making call to dataverse for multiple execute operation 

### ISSUE THREAD

**Issue by vedg** [AzureAD/microsoft-authentication-library-for-dotnet#4421]
### Library version used

4.57.0

### .NET version

6.0.416

processArchitecture: X64
osArchitecture: X64

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

1.Install PowerApps CLI
2. Open PowerShell
Run command " pac paportal download -id c8861521-b852-4f7a-af86-521959c6af12 -p C:\portal\Portaldownload "
3. Observed

![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/5424608/b960f99a-e29b-4207-903e-89430df99c17)

Session details for another user/client machine
 Product Version: 1.29.2+g86f5d33; File Version: 1.29.2
2023-11-10 13:20:38.7478 | INF | bolt.Session :: Start new session. (sessionId: 7ebec7a1-a17d-4655-a99a-9a5cbbf22831; operationId: 74b8d128a76069b4fd9dd7686a7f9903; userId: f21be0e7-e204-455c-a9f5-737ac2ad2d12; nonInteractiveMode: False)
2023-11-10 13:20:38.9101 | INF | bolt.cli.CommandProcessor :: StartExecutingVerb (Verbs: ["paportal","upload"])

 bolt.authentication.store.AuthTokenStore :: Successfully acquired a token using profile of type User for scope 'https://org870b261e.crm10.dynamics.com//.default'
2023-11-10 13:21:36.9093 | ERR | Microsoft.PowerPlatform.Dataverse.Client.ServiceClient :: ************ AggregateException - InitializeFileBlocksUpload : Execute (InitializeFileBlocksUpload) request to Dataverse from IOrganizationService |=> One or more errors occurred.
Source: mscorlib
Method: ThrowIfExceptional
DateUTC: 10-11-2023
TimeUTC: 13:21:36
Error: One or more errors occurred.
HelpLink Url: Not Provided
Stack Trace: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.Command_Execute(OrganizationRequest req, String errorStringCheck, Boolean bypassPluginExecution)
======================================================================================================================
Inner Exception Level 1	: 
==DataverseOperationException Info=======================================================================================
Source: Microsoft.PowerPlatform.Dataverse.Client
Error: External Authentication Requested but not configured correctly. 005
ErrorCode: -2146233088
DateUTC: 10-11-2023
TimeUTC: 13:21:36
HelpLink Url: Not Provided
======================================================================================================================
Inner Exception Level 2	: 
Source: Microsoft.Identity.Client.Extensions.Msal
Method: VerifyPersistence
DateUTC: 10-11-2023
TimeUTC: 13:21:36
Error: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
HelpLink Url: Not Provided
Stack Trace: at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
   at bolt.authentication.store.MsalExtensionCache.<CreateCacheHelperAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthApplication..ctor(IAuthKindDescription authKind, Uri authorityUri, MsalLoggingOptions msalLoggingOptions, IEnvirons environs, IProcessLauncher processLauncher, ILoggerFactory loggerFactory, IFeatureFlags featureFlags, Boolean useBrokerIfAvailable)
   at bolt.authentication.store.AuthTokenStore.<AcquireTokenSilentAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthTokenStore.<FetchTokenFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.dataverse.client.AuthWrapper.<GetAuthTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
======================================================================================================================
|EXCEPTION: Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseOperationException: External Authentication Requested but not configured correctly. 005 ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
   at bolt.authentication.store.MsalExtensionCache.<CreateCacheHelperAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthApplication..ctor(IAuthKindDescription authKind, Uri authorityUri, MsalLoggingOptions msalLoggingOptions, IEnvirons environs, IProcessLauncher processLauncher, ILoggerFactory loggerFactory, IFeatureFlags featureFlags, Boolean useBrokerIfAvailable)
   at bolt.authentication.store.AuthTokenStore.<AcquireTokenSilentAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthTokenStore.<FetchTokenFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.dataverse.client.AuthWrapper.<GetAuthTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
   at bolt.authentication.store.MsalExtensionCache.<CreateCacheHelperAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthApplication..ctor(IAuthKindDescription authKind, Uri authorityUri, MsalLoggingOptions msalLoggingOptions, IEnvirons environs, IProcessLauncher processLauncher, ILoggerFactory loggerFactory, IFeatureFlags featureFlags, Boolean useBrokerIfAvailable)
   at bolt.authentication.store.AuthTokenStore.<AcquireTokenSilentAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthTokenStore.<FetchTokenFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.dataverse.client.AuthWrapper.<GetAuthTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
2023-11-10 13:21:36.9252 | ERR | Microsoft.PowerPlatform.Dataverse.Client.ServiceClient :: [TerminalFailure] Failed to Execute Command - InitializeFileBlocksUpload : RequestID=204d3e17-d76d-4fce-a6e2-f5ed2c4fd15c : Execute (InitializeFileBlocksUpload) request to Dataverse from IOrganizationService duration=00:00:04.6621884 ExceptionMessage = One or more errors occurred.
|EXCEPTION: Microsoft.PowerPlatform.Dataverse.Client.Utils.DataverseOperationException: External Authentication Requested but not configured correctly. 005 ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
   at bolt.authentication.store.MsalExtensionCache.<CreateCacheHelperAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthApplication..ctor(IAuthKindDescription authKind, Uri authorityUri, MsalLoggingOptions msalLoggingOptions, IEnvirons environs, IProcessLauncher processLauncher, ILoggerFactory loggerFactory, IFeatureFlags featureFlags, Boolean useBrokerIfAvailable)
   at bolt.authentication.store.AuthTokenStore.<AcquireTokenSilentAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthTokenStore.<FetchTokenFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.dataverse.client.AuthWrapper.<GetAuthTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()
Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
   at bolt.authentication.store.MsalExtensionCache.<CreateCacheHelperAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthApplication..ctor(IAuthKindDescription authKind, Uri authorityUri, MsalLoggingOptions msalLoggingOptions, IEnvirons environs, IProcessLauncher processLauncher, ILoggerFactory loggerFactory, IFeatureFlags featureFlags, Boolean useBrokerIfAvailable)
   at bolt.authentication.store.AuthTokenStore.<AcquireTokenSilentAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.authentication.store.AuthTokenStore.<FetchTokenFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.dataverse.client.AuthWrapper.<GetAuthTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Dataverse.Client.ConnectionService.<RefreshClientTokenAsync>d__217.MoveNext()

### Relevant code snippets
We are using ServiceClient DataverseServiceClient  to perform the operation of dataverse records fetch and upload

### Expected behavior
We were not observing the above issue when we were using older version of MSAL library. this has started happening with the latest version - 4.57.0

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
Hi @vedg - is this happening all the time? How did you setup MSAL and how did you setup the cache? What operating system are you on? Is it Linux or WSL?

**Comment by vedg** [comment]
@petrochuk can you please add the details on how the setup of MSAL was done? also on cache layer? 

operating system is Windows

**Comment by vedg** [comment]
closing this as we are making change on client to handle the concurrency issue.
