### ISSUE TITLE
[Bug] NullReferenceException when using AcquireTokenSilent(scopes, loginHint)

### ISSUE THREAD

**Issue by msft-robertxu** [AzureAD/microsoft-authentication-library-for-dotnet#4431]
### Library version used

4.51.0

### .NET version

4.7.2

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

In our telemetry, I am seeing a huge number of errors coming from the package with `NullReferenceException`.

We are using `clientApp.AcquireTokenSilent(scopes, userEmail).ExecuteAsync()`

From the stack trace, the culprit seems to be this line:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/d98e56ed74f632c127f52ed1b8ff67c22fbefa50/src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs#L301C28-L301C141

```
_logger?.WarningPii(
    $"[WamBroker] Could not find a WAM account for the selected user {acquireTokenSilentParameters.Account.Username}. Error: {readAccountResult.Error}",
    $"[WamBroker] Could not find a WAM account for the selected user. Error: {readAccountResult.Error}");
```

Since I am not passing in an account, but a `loginHint` instead, I think `acquireTokenSilentParameters.Account` is null, and therefore trying to get the `Username` is causing a null reference error. 

Here is the stack trace:
```
 {
    "ExceptionType":"System.NullReferenceException",
    "ExceptionDetails":
    {
        "Message":"NullReferenceException",
        "StackTrace": "NullReferenceException
    at Microsoft.Identity.Client.Broker.RuntimeBroker.\\u003cAcquireTokenSilentAsync\\u003ed__16.MoveNext()
     --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.\\u003cSendTokenRequestToBrokerAsync\\u003ed__10.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.Identity.Client.Internal.Requests.BrokerSilentStrategy.\\u003cExecuteAsync\\u003ed__9.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.\\u003cExecuteAsync\\u003ed__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.Identity.Client.Internal.Requests.RequestBase.\\u003cRunAsync\\u003ed__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.\\u003cExecuteAsync\\u003ed__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.PowerBI.Client.Windows.PowerBIService.ActiveDirectoryAuthenticationContext.\\u003cAcquireTokenSilentAsync\\u003ed__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.PowerBI.Client.Windows.PowerBIService.AuthenticationManager.\\u003cAcquireTokenAsync\\u003ed__70.MoveNext()"
 }}
````

### Relevant code snippets

```csharp
var paramBuilder = clientApp.AcquireTokenSilent(scopes, userEmail)
```

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
@msft-robertxu - can you please try with the latest MSAL library? I do believe this bug was fixed.

**Comment by msft-robertxu** [comment]
Got it. I'll go ahead and close this for now. We're updating to the latest MSAL version (but doesn't roll out to customers until January or February). I haven't been able to get a repro locally (since it involves an error state already) so I'll have to wait until our next release cycle and see if the same exception happens.
