### ISSUE TITLE
[Bug] AADSTS50091: Passed query string length exceeds supported limit

### ISSUE THREAD

**Issue by Veverke** [AzureAD/microsoft-authentication-library-for-dotnet#4517]
### Library version used

4.56.0.0

### .NET version

.NET Framework 4.7.2

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

I am moving an azure app deprecated code to a new repo.
The api call requires creating a token, using the code below:

```
var token = (await ConfidentialClientApplicationBuilder.Create(_clientId).WithCertificate(_certificate).WithAuthority(authorityUri)
    .Build()
    .AcquireTokenForClient(new string[1] { $"{uri}{scope}" })
    .WithSendX5C(withSendX5C: true)
    .ExecuteAsync()
    .ConfigureAwait(continueOnCapturedContext: false)).AccessToken;
```

Isolating all the chained calls with a try/catch on each, the one that throws the error is ExecuteAsync (this may say nothing, given the others might only set flags/configure settings. Anyway...).

I have ran out of ideas on how to troubleshoot this.
client id, certificate, uri, scope all seem to be good (uri is the format https://{host}/{guid}. scope is "./default")

- uri+scope together has a length of 81.

- authorityUri is in the format https://login.microsoftonline.com/{...} and has a length of 61

- This specific error is not listed in the [common exceptions in MSAL docs](https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/exceptions/msal-error-handling).

**How do I find what is it that is exceeding the limit in the uri** (and which uri is it...) **?!**

**Update**

Adding .WithLogging(...) to the client app builder, with verbose logging, I get:

IdentityLog: Error - True MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-16 18:10:02Z - f5b6a166-7cdb-4da5-b069-5479d4845bc8] === Token Acquisition (1004) failed:
	Authority: https://login.microsoftonline.com/[my-uri]/
	ClientId: (skipped for brevity)
**IdentityLog: Error - True MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-16 18:10:02Z - f5b6a166-7cdb-4da5-b069-5479d4845bc8] MSAL.Desktop.4.56.0.0.MsalServiceException: 
	ErrorCode: invalid_request
Microsoft.Identity.Client.MsalServiceException: AADSTS50091: Passed query string length exceeds supported limit. Trace ID: 181810c0-2854-46b0-bbfc-1d219d4ab100 Correlation ID: f5b6a166-7cdb-4da5-b069-5479d4845bc8 Timestamp: 2024-01-16 18:09:59Z**
	**StatusCode: 400 
	ResponseBody: {"error":"invalid_request","error_description":"AADSTS50091: Passed query string length exceeds supported limit. Trace ID: 181810c0-2854-46b0-bbfc-1d219d4ab100 Correlation ID: f5b6a166-7cdb-4da5-b069-5479d4845bc8 Timestamp: 2024-01-16 18:09:59Z","error_codes":[50091],"timestamp":"2024-01-16 18:09:59Z","trace_id":"181810c0-2854-46b0-bbfc-1d219d4ab100","correlation_id":"f5b6a166-7cdb-4da5-b069-5479d4845bc8"} 
	Headers: Connection: keep-alive**
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
client-request-id: f5b6a166-7cdb-4da5-b069-5479d4845bc8
x-ms-request-id: 181810c0-2854-46b0-bbfc-1d219d4ab100
x-ms-ests-server: 2.1.16986.9 - EUS ProdSlices
x-ms-clitelem: 1,50091,0,,
X-XSS-Protection: 0
Cache-Control: no-store, no-cache
Date: Tue, 16 Jan 2024 18:09:59 GMT
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: fpc=Ag2aYXFeT1hIiUgr_yATlohtmvsTAQAAAHa9ON0OAAAA; expires=Thu, 15-Feb-2024 18:09:59 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly
X-Cache: CONFIG_NOCACHE

IdentityLog: Verbose - True MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-16 18:10:02Z - f5b6a166-7cdb-4da5-b069-5479d4845bc8] Finished TokenClient:SendTokenRequestAsync in 570 ms
IdentityLog: Error - True MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-16 18:10:02Z - f5b6a166-7cdb-4da5-b069-5479d4845bc8] MSAL.Desktop.4.56.0.0.MsalServiceException: 
	ErrorCode: invalid_request
Microsoft.Identity.Client.MsalServiceException: AADSTS50091: Passed query string length exceeds supported limit. Trace ID: 181810c0-2854-46b0-bbfc-1d219d4ab100 Correlation ID: f5b6a166-7cdb-4da5-b069-5479d4845bc8 Timestamp: 2024-01-16 18:09:59Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<GetTokenAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendHttpAndClearTelemetryAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendHttpAndClearTelemetryAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendTokenRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<GetAccessTokenAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
	StatusCode: 400 
	ResponseBody: {"error":"invalid_request","error_description":"AADSTS50091: Passed query string length exceeds supported limit. Trace ID: 181810c0-2854-46b0-bbfc-1d219d4ab100 Correlation ID: f5b6a166-7cdb-4da5-b069-5479d4845bc8 Timestamp: 2024-01-16 18:09:59Z","error_codes":[50091],"timestamp":"2024-01-16 18:09:59Z","trace_id":"181810c0-2854-46b0-bbfc-1d219d4ab100","correlation_id":"f5b6a166-7cdb-4da5-b069-5479d4845bc8"} 
	Headers: Connection: keep-alive
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
client-request-id: f5b6a166-7cdb-4da5-b069-5479d4845bc8
x-ms-request-id: 181810c0-2854-46b0-bbfc-1d219d4ab100
x-ms-ests-server: 2.1.16986.9 - EUS ProdSlices
x-ms-clitelem: 1,50091,0,,
X-XSS-Protection: 0
Cache-Control: no-store, no-cache
Date: Tue, 16 Jan 2024 18:09:59 GMT
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: fpc=Ag2aYXFeT1hIiUgr_yATlohtmvsTAQAAAHa9ON0OAAAA; expires=Thu, 15-Feb-2024 18:09:59 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly
X-Cache: CONFIG_NOCACHE

### Expected behavior

ExecuteAsync should complete without throwing exceptions.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by Veverke** [comment]
Turned out one of the secrets we were sending the app was incorrect.
The flow inadvertently continued with a malformed uri, somewhere.
Closing as not-an-issue.
