### ISSUE TITLE
[Bug] MsalCacheHelper Fails on iOS - PlatformNotSupportedException

### ISSUE THREAD

**Issue by timmac-qmc** [AzureAD/microsoft-authentication-library-for-dotnet#4708]
### Library version used

4.60.2

### .NET version

8.0

### Scenario

PublicClient - mobile app

### Is this a new or an existing app?

This is a new app or experiment

### Issue description and reproduction steps

Using the a attached code results in the exception below on iOS

`   at System.Diagnostics.ProcessManager.CreateProcessInfo(Int32 pid)
   at System.Diagnostics.ProcessManager.GetProcessInfo(Int32 processId, String machineName)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.Identity.Client.Extensions.Msal.SharedUtilities.GetCurrentProcessId()
   at Microsoft.Identity.Client.Extensions.Msal.CrossPlatLock..ctor(String lockfilePath, Int32 lockFileRetryDelay, Int32 lockFileRetryCount)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateCrossPlatLock(StorageCreationProperties storageCreationProperties)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateAsync(StorageCreationProperties storageCreationProperties, TraceSource logger)`

### Relevant code snippets

```csharp
private async Task BuildCache()
        {
            // This hooks up the cross-platform cache into MSAL
            if (_msalCacheHelper == null)
            {
                try
                {
                    var storageProperties = new StorageCreationPropertiesBuilder(AzureADConfig.CacheFileName, AzureADConfig.CacheDir)
#if MACCATALYST
                 .WithMacKeyChain(
                     AzureADConfig.KeyChainServiceName,
                     AzureADConfig.KeyChainAccountName)
#endif
                     .Build();

                    _msalCacheHelper = await MsalCacheHelper.CreateAsync(storageProperties);
                    _msalCacheHelper.RegisterCache(authenticationClient.UserTokenCache);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex);
                }
            }
        }
```

### Expected behavior

The iOS app should use the provided cache file without error

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by bgavrilMS** [comment]
This is expected, on iOS you do not need to set any caching, MSAL does it for you. MsalCacheHelper is only for desktop OS (Win Mac and Linux).

**Comment by chuckgiddens** [comment]
Yes, Maui iOS documentation is the worst...seems like they only care about Android...and none of my users have Android.
