### ISSUE TITLE
[Bug] MsalServiceException: AADSTS5002730: Invalid JWT token. Unsupported key for the signing algorithm

### ISSUE THREAD

**Issue by shenyue0625** [AzureAD/microsoft-authentication-library-for-dotnet#4712]
### Library version used

4.60.0

### .NET version

7.0

### Scenario

ConfidentialClient - service to service (AcquireTokenForClient)

### Is this a new or an existing app?

The app is in production, I haven't upgraded MSAL, but started seeing this issue

### Issue description and reproduction steps

Our app are using confidentialClient trying to acquire an access token so we can call another service's api. This process has failed with the following error, and checked on official doc but not seeing details for this AADSTS50027 specific error and how to resolve it. 

https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes
![image](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/assets/57239328/8577db7b-060a-482c-a054-f3de07bce506)

**2024-04-09T10:40:59.549243708Z fail: MoverAlmService[0]
2024-04-09T10:40:59.549276608Z       Unhandled exception
2024-04-09T10:40:59.549283908Z       MSAL.NetCore.4.60.0.0.MsalServiceException:
2024-04-09T10:40:59.549289208Z       	ErrorCode: invalid_request
2024-04-09T10:40:59.549296708Z       Microsoft.Identity.Client.MsalServiceException: AADSTS5002730: Invalid JWT token. Unsupported key for the signing algorithm. Trace ID: 1aefd40a-34ac-49a3-be3e-ffddbbfe9d00 Correlation ID: 17e5c2f0-4df6-4ff8-a56a-affb6ab81dec Timestamp: 2024-04-09 10:40:57Z
2024-04-09T10:40:59.549302508Z          at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
2024-04-09T10:40:59.549307908Z          at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
2024-04-09T10:40:59.549315008Z          at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
2024-04-09T10:40:59.549320308Z          at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
2024-04-09T10:40:59.549325108Z          at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ILoggerAdapter logger)
2024-04-09T10:40:59.549330608Z          at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
2024-04-09T10:40:59.549336208Z          at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
2024-04-09T10:40:59.549341908Z          at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
2024-04-09T10:40:59.549346908Z          at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
2024-04-09T10:40:59.549352408Z          at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
2024-04-09T10:40:59.549357508Z       --- End of stack trace from previous location ---
2024-04-09T10:40:59.549363208Z          at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
2024-04-09T10:40:59.549368808Z          at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
2024-04-09T10:40:59.549374108Z          at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
2024-04-09T10:40:59.549399608Z          at IdentityClientAdapter.GetAccessToken(IEnumerable`1 scopes) in /source/mover-alm/Services/MoverAlmService.cs:line 34
2024-04-09T10:40:59.549408108Z          at MoverAlmService.SendContainerMetadataToODSPSecurity(BlobMetadata blobMetadata, Conf settings, IIdentityClientAdapter confidentialApp, HttpClient client, AuditLogType auditLogType) in /source/mover-alm/Services/MoverAlmService.cs:line 148
2024-04-09T10:40:59.549413508Z       	StatusCode: 400 
2024-04-09T10:40:59.549419108Z       	ResponseBody: {"error":"invalid_request","error_description":"AADSTS5002730: Invalid JWT token. Unsupported key for the signing algorithm. Trace ID: 1aefd40a-34ac-49a3-be3e-ffddbbfe9d00 Correlation ID: 17e5c2f0-4df6-4ff8-a56a-affb6ab81dec Timestamp: 2024-04-09 10:40:57Z","error_codes":[5002730],"timestamp":"2024-04-09 10:40:57Z","trace_id":"1aefd40a-34ac-49a3-be3e-ffddbbfe9d00","correlation_id":"17e5c2f0-4df6-4ff8-a56a-affb6ab81dec"} 
2024-04-09T10:40:59.549424308Z       	Headers: Cache-Control: no-store, no-cache
2024-04-09T10:40:59.549429108Z       Pragma: no-cache
2024-04-09T10:40:59.549434408Z       Strict-Transport-Security: max-age=31536000; includeSubDomains
2024-04-09T10:40:59.549439208Z       X-Content-Type-Options: nosniff
2024-04-09T10:40:59.549444108Z       P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
2024-04-09T10:40:59.549449008Z       client-request-id: 17e5c2f0-4df6-4ff8-a56a-affb6ab81dec
2024-04-09T10:40:59.549453609Z       x-ms-request-id: 1aefd40a-34ac-49a3-be3e-ffddbbfe9d00
2024-04-09T10:40:59.549458109Z       x-ms-ests-server: 2.1.17750.6 - WUS3 ProdSlices
2024-04-09T10:40:59.549463009Z       x-ms-clitelem: 1,5002730,0,,
2024-04-09T10:40:59.549467609Z       x-ms-srs: 1.P
2024-04-09T10:40:59.549472309Z       X-XSS-Protection: 0
2024-04-09T10:40:59.549477309Z       Set-Cookie: fpc=AkQxgoA-33hOqfSMLG8o2b7tw1-HAQAAADgSp90OAAAA; expires=Thu, 09-May-2024 10:40:57 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; httponly
2024-04-09T10:40:59.549482009Z       Date: Tue, 09 Apr 2024 10:40:56 GMT
2024-04-09T10:40:59.549486909Z**       

The error seems happened with the client cert with wrong sign alogrithm issue, but not sure what's the supported algorithm here?

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

**Comment by pmaytak** [comment]
This is a duplicate of #4690 which was fixed in [4.60.1](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/releases/tag/4.60.1). Please upgrade to the latest version.
