### ISSUE TITLE
Implement Client Credential Flow

### ISSUE THREAD

**Issue by salvatore-garrubba** [AzureAD/microsoft-authentication-library-for-dotnet#493]
A ConfidentialClientApplication can only acquire token after an interaction with a user, which means using the Authorization Code Grant flow.
We would like to make service to service calls, aka Client Credential Flow, in order to acquire tokens and access protected resources.

**Comment by kpanwar** [comment]
You should use https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev/src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs#L136

**Comment by salvatore-garrubba** [comment]
@kpanwar: I tried but I always receive an error of grant type unsupported:

> Exception message: AADB2C90086: The supplied grant_type [client_credentials] is not supported.

This is the stack trace:

```
Exception stack trace:    at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.CreateErrorResponse(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.<ExecuteRequest>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.OAuth2.OAuth2Client.<GetToken>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendHttpMessageAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<SendTokenRequestAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<SendTokenRequestAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenForClientCommonAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ConfidentialClientApplication.<AcquireTokenForClientAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ConsoleApp1.Program.<Main>d__0.MoveNext() in {some-directory}\Program.cs:line 25
```

This is the code I used:

```
using Microsoft.Identity.Client;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace B2CClientCredentialFlowTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                var clientId = "CLIENT_ID";
                var secret = "CLIENT_SECRET";
                var redirectUri = "REDIRECT_URI";
                var aadInstance = "https://login.microsoftonline.com/tfp/{0}/{1}/v2.0/.well-known/openid-configuration";
                var tenant = "TENANT";
                var defaultPolicy = "POLICY";
                var authority = String.Format(aadInstance, tenant, defaultPolicy);
                var scope = new List<string> { "SCOPE" };
                var app = new ConfidentialClientApplication(clientId, authority, redirectUri, new ClientCredential(secret), new TokenCache(), null);
                var result = await app.AcquireTokenForClientAsync(scope).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception message: " + ex.Message);
                Console.WriteLine("Exception stack trace: " + ex.StackTrace);
                Console.ReadLine();
            }
        }
    }
}
```

Am I doing something wrong?
