### ISSUE TITLE
[Bug] Can not login with MSAL on Virtual Machine after updating MSAL.NET packages from 4.59.0

### ISSUE THREAD

**Issue by AnzarN** [AzureAD/microsoft-authentication-library-for-dotnet#4974]
### Library version used

Microsoft.Identity.Client.Broker 4.61.0 and Microsoft.Identity.Client.Extension.Msal 4.61.0

### .NET version

.net 8.0
WinAppSDK 1.6 (It is not working in WinAppSDK 1.5 as well)

### Scenario

PublicClient - desktop app

### Is this a new or an existing app?

The app is in production, and I have upgraded to a new version of MSAL

### Issue description and reproduction steps

Login is working on physical machine, but on virtual machine, MSAL dialog open but can't login, after clicking on email from list, the dialog close but there is no further process, if Microsoft.Identity package version is more than 4.59.0 
If I downgrade version to 4.59.0 it is working fine.

### Expected behavior

It should work even if I update package to more than 4.59.0 version.

### Identity provider

Microsoft Entra ID (Work and School accounts and Personal Microsoft accounts)

### Regression

4.59.0

### Solution and workarounds

Downgrade to version 4.59.0 working fine, issue with version more than 4.59.0

**Comment by AnzarN** [comment]
@iulico-1, Yes I have enable broker flow in my app but I am not running my app as Administrator on my Virtual Machine

**Comment by iulico-1** [comment]
@AnzarN , please share a screenshot of the UX you select account from ? Are you getting an exception from MSAL.net ?

**Comment by iulico-1** [comment]
@AnzarN, please share the content of AdditionalExceptionData and the full content of StackTrace from the exception.

**Comment by AnzarN** [comment]
Here is the StackTrace and AdditionalExceptionData

StackTrace:
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<SignInInteractivelyAsync>d__13.MoveNext()
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<AcquireTokenInteractiveAsync>d__12.MoveNext()
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.<FetchTokensAsync>d__9.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<FetchTokensFromBrokerAsync>d__10.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
   at Microsoft.Identity.Client.Utils.StopwatchService.<MeasureCodeBlockAsync>d__4.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__11.MoveNext()
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
   at bsone.uplift.Core.Services.AzureAuthService.<LoginAADInteractive>d__17.MoveNext() in C:\Users\azureadmin\Source\Repos\bsone.uplift\App\bsone.uplift.core\Services\AzureAuthService.cs:line 155


AdditionalExceptionData:

Microsoft.Identity.Client.MsalClientException
  HResult=0x80131500
  Message=User canceled authentication. 
  Source=Microsoft.Identity.Client.Broker
  StackTrace:
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult, AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<SignInInteractivelyAsync>d__13.MoveNext()
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.<AcquireTokenInteractiveAsync>d__12.MoveNext()
   at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.<FetchTokensAsync>d__9.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<FetchTokensFromBrokerAsync>d__10.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
   at Microsoft.Identity.Client.Utils.StopwatchService.<MeasureCodeBlockAsync>d__4.MoveNext()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__11.MoveNext()
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
   at bsone.uplift.Core.Services.AzureAuthService.<LoginAADInteractive>d__17.MoveNext() in C:\Users\azureadmin\Source\Repos\bsone.uplift\App\bsone.uplift.core\Services\AzureAuthService.cs:line 155

  This exception was originally thrown at this call stack:
    [External Code]
    bsone.uplift.Core.Services.AzureAuthService.LoginAADInteractive(System.Collections.Generic.List<string>) in AzureAuthService.cs

**Comment by ashok672** [comment]
@AnzarN - Based on the symptoms in the video shown, it looks like an issue we fixed. Can you try upgrading to 4.67 and also make sure the Microsoft.Identity.Client.NativeInterop version is 0.17.1. This is dependency from Microsoft.Identity.Client.Broker which can be updated to any latest version.

**Comment by AnzarN** [comment]
Upgrading the packages to version 4.67 and adding Microsoft.Identity.Client.NativeInterop version 0.17.1 resolved the issue.
