### ISSUE TITLE
.NET Core 2.0 Console App: NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by mazong1123** [AzureAD/microsoft-authentication-library-for-dotnet#557]
Seems like `PublicClientApplication` does not support .NET Core 2.0 Console App. Why does it call UI components?

```
   at Microsoft.Identity.Client.Internal.UI.WebUIFactory.CreateAuthenticationDialog(UIParent parent, RequestContext requestContext)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenForLoginHintCommonAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.PublicClientApplication.<AcquireTokenAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.HotPot.Tool.Exchange.AuthenticationHelper.<GetTokenForUserAsync>d__7.MoveNext() in D:\WorkSpace\personal\HotPot\src\dev\Tool\Exchange\AuthenticationHelper.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.HotPot.Tool.Exchange.AuthenticationHelper.<>c.<<GetAuthenticatedClient>b__6_0>d.MoveNext() in D:\WorkSpace\personal\HotPot\src\dev\Tool\Exchange\AuthenticationHelper.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__32`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.MailFolderMessagesCollectionRequest.<GetAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.HotPot.Tool.Exchange.ExchangeClient.<>c__DisplayClass0_0.<<GetCurrentUserFolders>b__0>d.MoveNext() in D:\WorkSpace\personal\HotPot\src\dev\Tool\Exchange\ExchangeClient.cs:line 18
```

**Comment by jennyf19** [comment]
@mazong1123  as you mentioned, .NET Core does not have UI components, and due to the multi-platform targeting of the library, we had to the following for .NET Core: 
```  internal class WebUIFactory : IWebUIFactory
    {
        public IWebUI CreateAuthenticationDialog(UIParent parent, RequestContext requestContext)
        {
            throw new NotImplementedException();
        }
    }
```
Using #ifdefs in the [PublicClientApplication](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev/src/Microsoft.Identity.Client/PublicClientApplication.cs) class was not sufficient and caused issues on the other platforms. 

Appreciate the feedback and we have it in our backlog to investigate other ways of handling this, so .NET core does not have the option to call UI components.

Here is more information on [web browsers ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser) in MSAL, in case you are interested.

**Comment by mazong1123** [comment]
Do we have any ETA for this?

**Comment by jmprieur** [comment]
@mazong1123 on which platform do you want to run your .NET Core app? (Windows, Linux, Mac)?
For the moment, .NET Core does not bring a UI? (in particular we need a web browser).

**Comment by jennyf19** [comment]
@mazong1123 - Can you try this [branch](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/jennyf/removeUI) and let us know if it fixes the issue for you? 

When I tried this in our [combined library](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/tree/jennyf/removeUI), I had issues with the multi-targeting, but things are building fine for me in just the MSAL repo.

**Comment by mazong1123** [comment]
@jennyf19 Thanks I'll give it a try.

**Comment by jennyf19** [comment]
@mazong1123 - we are having issues w/the multi-targeting...we are going to discuss options as a team and we will get back to you.

**Comment by bgavrilMS** [comment]
Closing, please let us know if there are any other questions.
